### ISSUE TITLE
--album doesn't work in the import

### ISSUE THREAD

**Issue by patricksan** [jmathai/elodie#10]
I tried to execute this command:

```
./elodie.py import --source="~/Desktop/chris" --destination="/Volumes/Data/Pictures/elodie-photos" --album="Aniversario Chris" 
```

but it always return Usage message:

```
Usage: main.py import --source=<s> --destination=<d>
       main.py import --file=<f> --destination=<d>
       main.py update [--time=<t>] [--location=<l>] [--album=<a>] [--title=<t>] INPUT ...

```

If I remove the _--album_ it does work.

**Comment by jmathai** [comment]
`import` doesn't support `--album` for a few reasons. If a photo has album information in the EXIF it will be properly sorted.

`import` also doesn't support `--location`, `--time` or `--location`. The logic for these are in the `_update` function.

Closing for now. Re-open if you think it's critical to have support in for the `import` command.

**Comment by patricksan** [comment]
Great! Thanks.
I was just using the old documentation.
