### ISSUE TITLE
Fix ImportError: No module named click

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#102]
Hey,

Thanks for software - excited to have a play with it!

I have an error and, if it's something you're aware of, wondered if you can help me with a fix?:

```
Apple-MacBook-Pro:/ ldexterldesign$ cd Applications/Elodie
Apple-MacBook-Pro:Elodie ldexterldesign$ pwd
/Applications/Elodie
Apple-MacBook-Pro:Elodie ldexterldesign$ ./elodie.py import --destination="/Volumes/server/_foo" /Volumes/server/_todo/image/_foo
Traceback (most recent call last):
  File "./elodie.py", line 8, in <module>
    import click
ImportError: No module named click
```

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
Can you run `pip install -r requirements.txt` first?

On Monday, April 11, 2016, Lewis Dexter Litanzios <notifications@github.com>
wrote:

> Hey,
>
> Thanks for software - excited to have a play with it!
>
> I have an error and, if it's something you're aware of, wondered if you
> can help me with a fix?:
>
> '''
> Apple-MacBook-Pro:/ ldexterldesign$ cd Applications/Elodie
> Apple-MacBook-Pro:Elodie ldexterldesign$ pwd
> /Applications/Elodie
> Apple-MacBook-Pro:Elodie ldexterldesign$ ./elodie.py import
> --destination="/Volumes/server/_foo" /Volumes/server/_todo/image/_foo
> Traceback (most recent call last):
> File "./elodie.py", line 8, in
> import click
> ImportError: No module named click
> '''
>
> Hope to hear back
>
> Kind thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/102>
>


-- 
-- Snet form my mobl phoone

**Comment by ldexterldesign** [comment]
Thanks for quick reply

My bad, I did skip that install step

However, I now have the following error despite satisfying the `pyexiv2` dependancy - any thoughts?:

```
Apple-MacBook-Pro:Elodie ldexterldesign$ pwd
/Applications/Elodie
Apple-MacBook-Pro:Elodie ldexterldesign$ ls
Dockerfile		Readme.md		config.ini		configs			docs			elodie.py		package.json		tools
LICENSE			app			config.ini-sample	creative		elodie			elodie.spec		requirements.txt
Apple-MacBook-Pro:Elodie ldexterldesign$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests<3.0,>=2.9.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): send2trash<2.0,>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Apple-MacBook-Pro:Elodie ldexterldesign$ brew update
Already up-to-date.
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install exiftool
Warning: exiftool-10.11 already installed
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install boost --build-from-source
Warning: boost-1.60.0_1 already installed
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install pyexiv2
Warning: pyexiv2-0.3.2_1 already installed
Apple-MacBook-Pro:Elodie ldexterldesign$ ./elodie.py import --destination="/Volumes/server/_foo" /Volumes/server/_todo/image/_foo
ImportError: No module named pyexiv2

It looks like you don't have pyexiv2 installed, which Elodie requires for
geolocation. Please take a look at the installation steps in the readme:

https://github.com/jmathai/elodie#install-everything-you-need
```

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
@ldexterldesign run these commands. You can find these [instructions in the Readme](https://github.com/jmathai/elodie#install-everything-you-need).

```
brew update
brew install exiftool
brew install boost --build-from-source
brew install pyexiv2
```

**Comment by ldexterldesign** [comment]
I did, as you can see in my previous comment's code snippet:

```
Apple-MacBook-Pro:Elodie ldexterldesign$ brew update
Already up-to-date.
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install exiftool
Warning: exiftool-10.11 already installed
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install boost --build-from-source
Warning: boost-1.60.0_1 already installed
Apple-MacBook-Pro:Elodie ldexterldesign$ brew install pyexiv2
Warning: pyexiv2-0.3.2_1 already installed
```

Any other thoughts?

Thanks

**Comment by jmathai** [comment]
@ldexterldesign Mind trying what the last commenter on this issue did to resolve it?

https://github.com/jmathai/elodie/issues/25#issuecomment-176049629

**Comment by ldexterldesign** [comment]
Not sure what fixed it exactly, but I woke up this morning and tried running the cloned app from `/Users/ldexterldesign/Desktop` instead of root `/Applications` and it works great:

```bash
Apple-MacBook-Pro:Applications ldexterldesign$ cd ~/Desktop/
Apple-MacBook-Pro:Desktop ldexterldesign$ git clone https://github.com/jmathai/elodie.git
Cloning into 'elodie'...
remote: Counting objects: 1103, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1103 (delta 1), reused 0 (delta 0), pack-reused 1085
Receiving objects: 100% (1103/1103), 3.41 MiB | 763.00 KiB/s, done.
Resolving deltas: 100% (668/668), done.
Checking connectivity... done.
Apple-MacBook-Pro:Desktop ldexterldesign$ pip install -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Apple-MacBook-Pro:Desktop ldexterldesign$ cd elodie/
Apple-MacBook-Pro:elodie ldexterldesign$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): requests<3.0,>=2.9.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): send2trash<2.0,>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Apple-MacBook-Pro:elodie ldexterldesign$ brew update
Updated Homebrew from 496fff6 to 4e8c6e6.
Updated 1 tap (homebrew/core).
==> Updated Formulae
fswatch                      keybase                      libart                       libtasn1                     minimodem                    mysql                        saltstack                  
Apple-MacBook-Pro:elodie ldexterldesign$ brew install exiftool
Warning: exiftool-10.11 already installed
Apple-MacBook-Pro:elodie ldexterldesign$ brew install boost --build-from-source
==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
==> Patching
patching file boost/graph/adjacency_matrix.hpp
==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib --without-icu --without-libraries=python,mpi
==> ./b2 headers
==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib -d2 -j8 --layout=tagged --user-config=user-config.jam install threading=multi,single link=shared,static
🍺  /usr/local/Cellar/boost/1.60.0_1: 11,139 files, 433.6M, built in 11 minutes 45 seconds
Apple-MacBook-Pro:elodie ldexterldesign$ brew install pyexiv2
==> Installing dependencies for pyexiv2: scons, exiv2, boost-python
==> Installing pyexiv2 dependency: scons
==> Downloading https://homebrew.bintray.com/bottles/scons-2.4.1.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/scons-2.4.1.el_capitan.bottle.tar.gz
==> Pouring scons-2.4.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/scons/2.4.1: 211 files, 2.2M
==> Installing pyexiv2 dependency: exiv2
==> Downloading https://homebrew.bintray.com/bottles/exiv2-0.25.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/exiv2-0.25.el_capitan.bottle.tar.gz
==> Pouring exiv2-0.25.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/exiv2/0.25: 50 files, 7.5M
==> Installing pyexiv2 dependency: boost-python
==> Downloading https://homebrew.bintray.com/bottles/boost-python-1.60.0.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/boost-python-1.60.0.el_capitan.bottle.tar.gz
==> Pouring boost-python-1.60.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/boost-python/1.60.0: 274 files, 14.3M
==> Installing pyexiv2
==> Downloading https://launchpad.net/pyexiv2/0.3.x/0.3.2/+download/pyexiv2-0.3.2.tar.bz2
Already downloaded: /Library/Caches/Homebrew/pyexiv2-0.3.2.tar.bz2
==> Patching
patching file src/SConscript
==> /usr/local/opt/scons/bin/scons BOOSTLIB=boost_python-mt
🍺  /usr/local/Cellar/pyexiv2/0.3.2_1: 14 files, 573.9K, built in 7 seconds
```

Could have simply been a permissions issue before

Kind thanks for your help, and look forward to finally organising 10 years worth of images!

Regards

**Comment by jmathai** [comment]
Don't forget to add a MapQuest key so that the photos will be organized by
location.

Glad it's working now.

On Tuesday, April 12, 2016, Lewis Dexter Litanzios <notifications@github.com>
wrote:

> Not sure what fixed it exactly, but I woke up this morning and tried
> running the cloned app from /Users/ldexterldesign/Desktop instead of root
> /Applications and it works great:
>
> Apple-MacBook-Pro:Applications ldexterldesign$ cd ~/Desktop/
> Apple-MacBook-Pro:Desktop ldexterldesign$ git clone https://github.com/jmathai/elodie.git
> Cloning into 'elodie'...
> remote: Counting objects: 1103, done.
> remote: Compressing objects: 100% (17/17), done.
> remote: Total 1103 (delta 1), reused 0 (delta 0), pack-reused 1085
> Receiving objects: 100% (1103/1103), 3.41 MiB | 763.00 KiB/s, done.
> Resolving deltas: 100% (668/668), done.
> Checking connectivity... done.
> Apple-MacBook-Pro:Desktop ldexterldesign$ pip install -r requirements.txt
> Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
> Apple-MacBook-Pro:Desktop ldexterldesign$ cd elodie/
> Apple-MacBook-Pro:elodie ldexterldesign$ pip install -r requirements.txt
> Requirement already satisfied (use --upgrade to upgrade): click<7.0,>=6.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied (use --upgrade to upgrade): requests<3.0,>=2.9.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): send2trash<2.0,>=1.3.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
> Apple-MacBook-Pro:elodie ldexterldesign$ brew update
> Updated Homebrew from 496fff6 to 4e8c6e6.
> Updated 1 tap (homebrew/core).
> ==> Updated Formulae
> fswatch                      keybase                      libart                       libtasn1                     minimodem                    mysql                        saltstack
> Apple-MacBook-Pro:elodie ldexterldesign$ brew install exiftool
> Warning: exiftool-10.11 already installed
> Apple-MacBook-Pro:elodie ldexterldesign$ brew install boost --build-from-source
> ==> Downloading https://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2
> Already downloaded: /Library/Caches/Homebrew/boost-1.60.0.tar.bz2
> ==> Patching
> patching file boost/graph/adjacency_matrix.hpp
> ==> ./bootstrap.sh --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib --without-icu --without-libraries=python,mpi
> ==> ./b2 headers
> ==> ./b2 --prefix=/usr/local/Cellar/boost/1.60.0_1 --libdir=/usr/local/Cellar/boost/1.60.0_1/lib -d2 -j8 --layout=tagged --user-config=user-config.jam install threading=multi,single link=shared,static
> 🍺  /usr/local/Cellar/boost/1.60.0_1: 11,139 files, 433.6M, built in 11 minutes 45 seconds
> Apple-MacBook-Pro:elodie ldexterldesign$ brew install pyexiv2
> ==> Installing dependencies for pyexiv2: scons, exiv2, boost-python
> ==> Installing pyexiv2 dependency: scons
> ==> Downloading https://homebrew.bintray.com/bottles/scons-2.4.1.el_capitan.bottle.tar.gz
> Already downloaded: /Library/Caches/Homebrew/scons-2.4.1.el_capitan.bottle.tar.gz
> ==> Pouring scons-2.4.1.el_capitan.bottle.tar.gz
> 🍺  /usr/local/Cellar/scons/2.4.1: 211 files, 2.2M
> ==> Installing pyexiv2 dependency: exiv2
> ==> Downloading https://homebrew.bintray.com/bottles/exiv2-0.25.el_capitan.bottle.tar.gz
> Already downloaded: /Library/Caches/Homebrew/exiv2-0.25.el_capitan.bottle.tar.gz
> ==> Pouring exiv2-0.25.el_capitan.bottle.tar.gz
> 🍺  /usr/local/Cellar/exiv2/0.25: 50 files, 7.5M
> ==> Installing pyexiv2 dependency: boost-python
> ==> Downloading https://homebrew.bintray.com/bottles/boost-python-1.60.0.el_capitan.bottle.tar.gz
> Already downloaded: /Library/Caches/Homebrew/boost-python-1.60.0.el_capitan.bottle.tar.gz
> ==> Pouring boost-python-1.60.0.el_capitan.bottle.tar.gz
> 🍺  /usr/local/Cellar/boost-python/1.60.0: 274 files, 14.3M
> ==> Installing pyexiv2
> ==> Downloading https://launchpad.net/pyexiv2/0.3.x/0.3.2/+download/pyexiv2-0.3.2.tar.bz2
> Already downloaded: /Library/Caches/Homebrew/pyexiv2-0.3.2.tar.bz2
> ==> Patching
> patching file src/SConscript
> ==> /usr/local/opt/scons/bin/scons BOOSTLIB=boost_python-mt
> 🍺  /usr/local/Cellar/pyexiv2/0.3.2_1: 14 files, 573.9K, built in 7 seconds
>
> Could have simply been a permissions issue before
>
> Kind thanks for your help, and look forward to finally organising 10 years
> worth of images!
>
> Regards
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/102#issuecomment-208982411>
>


-- 
-- Snet form my mobl phoone

**Comment by naoj77** [comment]
Sorry in advance for my bad english.

I've the same error, and I tried in many folders and don't work

`iMac-de-JOAN:elodie joan$ pip install -r requirements.txt
Requirement already satisfied: click==6.6 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests==2.11.1 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: Send2Trash==1.3.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: future==0.16.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: configparser==3.5.0 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: tabulate==0.7.7 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 6))
iMac-de-JOAN:elodie joan$ ./elodie.py import --destination="/Volumes/photo/test" /Volumes/photo/copiafotosmobilJoan/FotosMobilJoan
Traceback (most recent call last):
  File "./elodie.py", line 9, in <module>
    import click
ImportError: No module named click
iMac-de-JOAN:elodie joan$ elodie.py verify
-bash: elodie.py: command not found`

any suggestions?

**Comment by jmathai** [comment]
Are you using virtualenv at all?

Can you try this by using the python shell?

```
# pip install -r requirements.txt
# python
> import click
```

**Comment by naoj77** [comment]
Thanks for your response.

I don't use virtualment? It's recommended or required?

I'll try this, but how can I launch Python shell?

Thanks a lot

El dia 17 gen. 2017 10.58 p. m., "Jaisen Mathai" <notifications@github.com>
va escriure:

Are you using virtualenv at all?

Can you try this by using the python shell?

# pip install -r requirements.txt
# python
> import click

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jmathai/elodie/issues/102#issuecomment-273313231>, or mute
the thread

**Comment by jmathai** [comment]
Type `python` into your shell.

**Comment by naoj77** [comment]
Don't work

iMac-de-JOAN:elodie joan$ python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> # pip install -r requirements.txt
... 
>>> # python
... # pip install -r requirements.txt
... # python
... > import click
  File "<stdin>", line 4
    > import click
    ^
SyntaxError: invalid syntax
>>> 

I've made something wrong?

**Comment by ldexterldesign** [comment]
FYI
NO REPLY NECESSARY

Just experienced this same issue and fixed it a bit more comprehensively this time with the #25 tip off

Pretty confident this time it's a OS X Python vs Homebrew Python issue which I fixed by reinstalling Homebrew Python version

NB You must call ``pip`` commands in Homebrew by using ``pip2``:

```
pip2 install -r requirements.txt
```

Unsure exactly how this works but it should install the requirements so Homebrew Python can access them

Hope this is clear/useful

Regards

**Comment by naoj77** [comment]
Thanks I'll try

El dia 2 nov. 2017 1.06 a. m., "Lewis Dexter Litanzios" <
notifications@github.com> va escriure:

**Comment by edwardfhsiao** [comment]
cuz I only have pip3, so it works when I change
```py
#!/usr/bin/env python
```
to
```py
#!/usr/bin/env python3
```
in the elodie.py file

**Comment by jmathai** [comment]
@edwardfhsiao I'm not sure of a way to have a shebang that invokes whatever python binary exists on the system. Open to recommendations though.

**Comment by edwardfhsiao** [comment]
@jmathai Just a reminder for anyone else like me who does not familiar with python. Great work though. :)
