### ISSUE TITLE
Clarify repeating import command

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#104]
Hey,

Thanks for software

I have things working well the first time I "import" `source` folder files. However if I delete my `destination` folder files and rerun the same import command nothing happens - I would expect the same `source` files to be processed into my `destination` folder - I'm trying to understand if this is a bug or a feature?

What's the expected behaviour for this use case?

I'm trying to get this working so I can [repeatedly] experiment on batches of files

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
There is a file at `~/.elodie/hash.json` which keeps track of files to
avoid duplicates. Simply remove that file and try the import again.

On Tuesday, April 12, 2016, Lewis Dexter Litanzios <notifications@github.com>
wrote:

> Hey,
>
> Thanks for software
>
> I have things working well the first time I import folder files. However
> if I delete my destination folder files and rerun the same import
> command, nothing happens - I'm trying to understand if this is a bug or a
> feature?
>
> What's the expected behaviour for this use case?
>
> I'm trying to get this working so I can test import batches of files to
> experiment on source files
>
> Hope to hear back
>
> Kind thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/104>
>


-- 
-- Snet form my mobl phoone

**Comment by ldexterldesign** [comment]
Thanks for quick reply

Damn, I wish I'd have asked sooner - would have saved myself a few hours!

Kind thanks

**Comment by jmathai** [comment]
@ldexterldesign Sorry about that. We should have more documentation for these things. Feel free to add them and submit a pull request. I created gh-105 for that.

You can set `debug=True` to have more verbose output.
https://github.com/jmathai/elodie/blob/master/elodie/constants.py#L8
