### ISSUE TITLE
Create/add/update documentation with argument list

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#106]
Hey,

I've looked hard, and I know some of them are new (e.g. https://github.com/jmathai/elodie/issues/104#issuecomment-209246169 ), but some comprehensive documentation for arguments would be useful (i.e. `--debug --destination --source --trash`)

I'll reference https://github.com/jmathai/elodie/issues/105 for your convenience

Hope this is useful

Regards

**Comment by jmathai** [comment]
@noonat is this something we can add to readthedocs? I'd prefer a `docs` folder with markdown files that are generated and hosted on our readthedocs documentation page instead of adding to the Readme. I prefer that the Readme be more focused on a higher level explanation of what Elodie can do than to be technical **how to use the software** documentation.

I closed #105 and we can use this issue to get the documentation set up.

**Comment by ldexterldesign** [comment]
FYI I usually review GitHub page summary (i.e. README) for documentation. Failing that I will look in the GitHub Wiki. If I still can't find it I will resort to the website, but they tend to have a habit of falling out of date pretty quickly, so lack integrity IMO.

I understand you plan to launch a website ( https://github.com/jmathai/elodie/issues/19 ), so using markdown templates you should be able to dynamically source the same content - win! ~ https://twitter.com/ldexterldesign/status/700148835893559296

Hope this helps

Regards

**Comment by jmathai** [comment]
@ldexterldesign I completely agree. I think we can make it clear via the readme where you should go. Worst case scenario if people are confused we can always bring the markdown back into the readme.

gh-19 hasn't seen much movement yet. I personally like the idea of a documentation page over a 'landing page'. I think both would be good though.

**Comment by ldexterldesign** [comment]
Something like http://sassdoc.com/ ?

Regards

**Comment by jmathai** [comment]
I'm not sure what @noonat used but he did the legwork to have documentation pulled from source code into readthedocs. http://elodie.readthedocs.org/en/latest/

That's more geared to someone who might want to use Elodie as a library in another project though. I'm hoping we can do similar (like sassdoc or included in what @noonat has done, ideally) for introductory **this is how you get started with Elodie and here are answers to all of your questions**.

**Comment by ldexterldesign** [comment]
Here are a few documentation generators I have noted:

- https://github.com/jsdoc3/jsdoc
- https://github.com/rtfd/readthedocs.org
- https://github.com/SassDoc/sassdoc

I almost had the need to use one a few years ago to document a front-end pattern library I was building for a company, but it didn't materialise - still curious about how they work

Perhaps @noonat has found something better since..?

I will research them sometime...

Regards

**Comment by jmathai** [comment]
Included the output from the command line program into the Readme.

https://github.com/jmathai/elodie/blob/master/Readme.md#usage-instructions
