### ISSUE TITLE
Allow destination file name structure to be customized

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#107]
Hey,

I see this issue has already been discussed for folder naming ( https://github.com/jmathai/elodie/issues/5 ), but I'd like to control the structure of [image] file naming

More specifically, retaining the filename during a "first pass" is useful as an ID, but I'd like the ability to remove the filename with a second pass; since I now have a unique timestamp:

<img width="1440" alt="screen shot 2016-04-14 at 03 09 23" src="https://cloud.githubusercontent.com/assets/1715809/14514154/63c9c0a8-01ee-11e6-8439-357e6175e97b.png">

Is this possible?

FYI I played with http://www.sno.phy.queensu.ca/~phil/exiftool/ a while back and decide the ideal naming structure for me would involve the following:

```
CreateDate: 2015:03:02 07:54:33 or SubSecCreateDate: 2015:03:02 07:54:33.33
DateTimeOriginal: 2015:03:02 07:54:33 or SubSecDateTimeOriginal: 2015:03:02 07:54:33.33
ImageSize: 3872x2592
Make: NIKON CORPORATION
Model: NIKON D200
```

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
Not possible currently. One issue with removing the file name is that the
possibility of a naming collision not uncommon. It's certainly possible
though. But I think it would fall under an option to control the file and
folder naming at a more general level.

Removing the file name itself would not be difficult. The code is probably
in filesystem.py. I'm traveling at the moment so I can't check.

On Wednesday, April 13, 2016, Lewis Dexter Litanzios <
notifications@github.com> wrote:

> Hey,
>
> I see this issue has already been discussed for folder naming ( #5
> <https://github.com/jmathai/elodie/issues/5> ), but I'd like to control
> the structure of [image] file naming
>
> More specifically, I'd like to remove the filename:
>
> [image: screen shot 2016-04-14 at 03 09 23]
> <https://cloud.githubusercontent.com/assets/1715809/14514154/63c9c0a8-01ee-11e6-8439-357e6175e97b.png>
>
> Is this possible and if so is there any documentation?
>
> Hope to hear back
>
> Kind thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/107>
>


-- 
-- Snet form my mobl phoone

**Comment by ldexterldesign** [comment]
Oh that's a shame, but I guess I can use another tool to finish that minor task off:

http://cfxsoftware.com/products/perfect-rename/
http://ilialang.com/apps/
http://ismartphoto.wordpress.com/
http://overmacs.com/?p=photomill
http://publicspace.net/BetterRename/

Have you considered enhancing the timestamp with `CreateDate: 2015:03:02 07:54:33 or SubSecCreateDate: 2015:03:02 07:54:33.33` to help prevent collisions?

I agree, is there an appropriate place to submit a feature request for custom EXIF file/folder name/structure?

Safe travels, and if you can review `filesystem.py` to see if this will help my cause I'd be grateful. Would be amazing to wrap up my needs with your tool alone

Yours hopefully

**Comment by jmathai** [comment]
@ldexterldesign my guess is that changing [these lines](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L122)....

```
        file_name = '%s-%s.%s' % (
            time.strftime(
                '%Y-%m-%d_%H-%M-%S',
                metadata['date_taken']
            ),
            base_name,
            metadata['extension'])
```

to this would omit the file name from the destination path.

```
        file_name = '%s.%s' % (
            time.strftime(
                '%Y-%m-%d_%H-%M-%S',
                metadata['date_taken']
            ),
            metadata['extension'])
```

**Comment by ldexterldesign** [comment]
Hey,

Apologies for delay

Thanks for reply

That worked. However, I tried some "burst" photos, which, as predicted, got munged:
<img width="345" alt="screen shot 2016-04-29 at 01 56 24" src="https://cloud.githubusercontent.com/assets/1715809/14905085/e5fc93e6-0dad-11e6-8239-d99c5beb3793.png">

Is there any documentation on `time.strftime()` function usage?

The addition of sub-second syntax should solve this...

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
How did t get munged? It should work okay as far as I know.

On Thursday, April 28, 2016, Lewis Dexter Litanzios <
notifications@github.com> wrote:

> Hey,
>
> Apologies for delay
>
> Thanks for reply
>
> That worked. However, I tried some "burst" photos, which, as predicted,
> got munged:
> [image: screen shot 2016-04-29 at 01 56 24]
> <https://cloud.githubusercontent.com/assets/1715809/14905085/e5fc93e6-0dad-11e6-8239-d99c5beb3793.png>
>
> Is there any documentation on time.strftime() function usage?
>
> The addition of sub-second syntax should solve this...
>
> Hope to hear back
>
> Kind thanks
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/107#issuecomment-215597229>
>


-- 
-- Snet form my mobl phoone

**Comment by ldexterldesign** [comment]
The two sets of burst images combined into two images, likely because they were taken within the same second

**Comment by jmathai** [comment]
Photos with the same file name and time taken (to the second)?

Did files get overwritten?

On Thursday, April 28, 2016, Lewis Dexter Litanzios <
notifications@github.com> wrote:

> The two sets of burst images combined into two images, likely because they
> were taken within the same second
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/107#issuecomment-215599370>
>


-- 
-- Snet form my mobl phoone

**Comment by ldexterldesign** [comment]
Well, there's no file name (i.e. `base_name`) now because I've implemented the script you suggested above, so yes

And yes - the would have been lost if I'd have used the `--trash`` option 😕

Regards

**Comment by ldexterldesign** [comment]
Here's the zip of burst images I'm working with if it helps https://drive.google.com/open?id=0B-oUmf4LFtExN05hMEoxVHJSRHM (6.9MB)

Hope this is useful

Regards

**Comment by jmathai** [comment]
Ah. That's self inflicted :). Here's the docs for strftime you can probably use to *fix* it. http://strftime.org/

**Comment by ldexterldesign** [comment]
Thanks

I thought I could fix this myself (*zero python knowledge*), but I'm struggling ~ https://stackoverflow.com/questions/6677332/using-f-with-strftime-in-python-to-get-microseconds

Are you able to help?

Yours hopefully

**Comment by ldexterldesign** [comment]
Completely by chance, I got the script outputting the `%f` microsecond by importing `datetime` class and tampering with the syntax using `datetime.datetime.now()`

```
file_name = '%s-%s.%s' % (
	datetime.datetime.strftime(metadata['date_taken'], '%Y-%m-%d_%H-%M-%S-%f'),
	base_name,
	metadata['extension'])
return file_name.lower()
```

It worked, but obviously now trying to pass in the correct date

```bash
Apple-MacBook-Pro:elodie ldexterldesign$ ./elodie.py import --source=/Users/ldexterldesign/Desktop/1 --destination=/Users/ldexterldesign/Desktop/3
Traceback (most recent call last):
  File "./elodie.py", line 232, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 98, in _import
    trash)
  File "./elodie.py", line 57, in import_file
    media, allowDuplicate=False, move=False)
  File "/Applications/elodie/elodie/filesystem.py", line 185, in process_file
    file_name = self.get_file_name(media)
  File "/Applications/elodie/elodie/filesystem.py", line 124, in get_file_name
    datetime.datetime.strftime(metadata['date_taken'], '%Y-%m-%d_%H-%M-%S-%f'),
TypeError: descriptor 'strftime' requires a 'datetime.date' object but received a 'time.struct_time'
```

If I'm on the right track would you be kind enough to help me make sense of `metadata['date_taken']`?

Yours hopefully

**Comment by jmathai** [comment]
EXIF dates [only have precision down to the seconds](http://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/datetimeoriginal.html). You need some sort unique attribute for the photo and EXIF time alone will not work for burst mode photos.

You could throw in a random number which decreases the chance of a collision or use part of the hash of the contents.

You can generate a random number using the following code.

```
# suggest putting this near the top of the file
from random import random

# then this to use the random number as a prefix
file_name = '%s-%s.%s' % (
    int(random()*100000),
    base_name,
    metadata['extension'])
return file_name.lower()
```

**Comment by ldexterldesign** [comment]
Apologies, I was under some weird impression http://www.sno.phy.queensu.ca/~phil/exiftool/ was creator/maintainer of the EXIF standard when it's just one of many tools (just read https://en.wikipedia.org/wiki/Exchangeable_image_file_format ) 🙄

Both my phone (Google Nexus 5) and camera (Nikon D200) are capable of taking sub-second photos, so I will need some way of distinguishing these - I'm aware the `base_name` will cater for this. However, for the "first pass", I'd like some way of deleting the base name from my photos, since I consider it messy.

I think I'll use the random number for the first pass and default back to base name moving forward

Thanks for your patience; I think you appreciate this is rather an edge case

Kind thanks

PS Is Would you consider adding sub-second output later, like http://www.sno.phy.queensu.ca/~phil/exiftool/ - if so may I create a feature request or add it to this issue (since it's still open, I gather you're open to the idea of custom file names/structures..?)

**Comment by jmathai** [comment]
@ldexterldesign was there somewhere on the exiftool page where you saw that dates stored in EXIF have subsecond precision? Everything I saw rounded to the nearest second.

This particular issue is open for implementation. I'm not sure how to address the issue of multiple photos taken at the same second by also removing the base_name; unless the random number approach is taken.

**Comment by ldexterldesign** [comment]
Some insightful stuff I found...

http://photo.net/nikon-camera-forum/00VCDH

> When extracting from file, timestamps are taken from the first available of the following tags:
>- Image timestamp: SubSecDateTimeOriginal, SubSecCreateDate, SubSecModifyDate, DateTimeOriginal, CreateDate, ModifyDate, FileModifyDate
>- GPS timestamp: GPSDateTime, GPSTimeStamp
http://www.sno.phy.queensu.ca/~phil/exiftool/geotag.html

>The values of the composite tags are Derived From the values of other tags. These are convenience tags which are calculated after all other information is extracted. Only a few of these tags are writable directly, the others are changed by writing the corresponding Derived From tags. User-defined Composite tags, also useful for custom-formatting of tag values, may created via the ExifTool configuration file.
http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/Composite.html

http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/Shortcuts.html

What do you make of it?

Hope this is useful/relevant

Regards

**Comment by jmathai** [comment]
With #160 I think we now have the foundation needed to allow for customized file names.

**Comment by ldexterldesign** [comment]
Thanks for follow up

Wonderful to hear!

Be sure to update this issue when it's complete so I can have a play/test

Let me know if you have any issues - happy to help

Hope to hear back

Kind thanks

**Comment by jmathai** [comment]
From #177 by @jalsin82

> In reading other posts, there seems to be a concern with duplicate filenames. Is it possible to handle any duplicate filename errors by appending an incrementing number to the complete filename?

An incremental number is difficult without adding another database which tracks the last number assigned.

One option is to include a randomized label which can be used in generating the file name. Something along the lines of this.

```
[File]
name=%year_%month_%day_%random.%ext
```

**Comment by jalsin82** [comment]
Since this is the only issue preventing me from implementing elodie across my and my wife's picture library, I'm still interested in the having elodie create a completely new and unique name.

I don't understand why a separate database would have to be used to track the last number assigned. When elodie creates a filename from the date and time, most of the time this filename will be unique. In the event that this method does not create a unique file name, why can't elodie just append an incrementing number to the filename - like Windows currently does. For example, if I select 4 files in Windows an rename them all simultaneously the result will be filename.ext, filename (1).ext, filename (2).ext, and filename (3).ext. If I select 4 more files in the same folder and rename them at the same time the result will be filename2.ext, filename2 (1).ext, filename2 (2).ext, and filename2 (3).ext. If I select 2 more files in the same folder and rename them with the same new filename as the first file the result will be filename (4).ext and filename (5).ext. 

Would it be possible for the rename routine to do something along the lines of:
build new filename in temporary variable
initialize temporary counter variable to 0
if new filename does not already exist: rename file to new filename
if new filename already exists: increment counter by 1, append incremented counter to filename, check if new filename with counter already exists
if the new filename with counter already exists: increment counter by 1, and repeat until unique filename is found
(obviously there would need to be some point in which it fails, but it's highly unlikely that there is going to be 1,000,000 pictures in one folder all with the same filename generated by elodie)

In this way, I would think elodie could create completely new and unique filenames for imported pictures without having to create additional databases to track a file counter.

You have done a very thorough job with elodie. So I have to believe that you have already considered this as a solution. So, I guess I'm really just curious as to why this solution does not work. And, then, I guess my request is to continue searching for an appropriate solution that allows elodie to generate a completely new and unique filename.

**Comment by jmathai** [comment]
@jalsin82 thanks for the detailed response. Your suggestion is how the operating system handles keeping two files with duplicate names. I know OS X adds a `copy X` to the end of the file name.

I'm not opposed to that behavior and I haven't considered it recently. I think this request is separate from this issue. This issue is actually a larger change so if you can open another issue I can probably get that in earlier.. Feel free to copy your comment above into it if you feel like it captures what you're requesting. We can outline the various scenarios and how the rename should work in that issue.

**Comment by jmathai** [comment]
I'm having a difficult time coming up with a method to support customized file names. There are a few edge cases I can't seem to elegantly address. We need to know the original file name in order to run the `update` command. We also need it if someone wanted to `import` a photo again. At the moment we don't store that anywhere but we can parse it out of the hard coded file name. Once the resulting file name becomes hard coded we can no longer parse it reliably.

It's probably time to store the original file name into EXIF when it is imported. It's an enhancement since it preserves more of the original photo's information than we already do and nothing else seems to preserve that.

I created #186 to track storing the original file name into EXIF.

Related issues - #177 #172

**Comment by ldexterldesign** [comment]
> I'm not sure how to address the issue of multiple photos taken at the same second by also removing the base_name; unless the random number approach is taken.


(obviously there would need to be some point in which it fails, but it's highly unlikely that there is going to be 1,000,000 pictures in one folder all with the same filename generated by elodie)



I'm not opposed to that behavior and I haven't considered it recently. I think this request is separate from this issue. This issue is actually a larger change so if you can open another issue I can probably get that in earlier.. Feel free to copy your comment above into it if you feel like it captures what you're requesting. We can outline the various scenarios and how the rename should work in that issue.

**Comment by ldexterldesign** [comment]
Hmm, it's not clear to me[0] whether we're now storing base names in EXIF on ``import``?:

If yes, I think this non-destructive approach is a good idea providing the user can clear this EXIF data later (e.g. they're happy with the file name)

One can find conversations on the use of tagging here:

https://github.com/metabrainz/picard
https://tickets.metabrainz.org/projects/PICARD/issues

NB https://tickets.metabrainz.org/browse/PICARD-287 - I pulled this up in a matter of seconds

--

I was going to leave the following comment in [0] but unsure of that issue's status so I'll leave it here

A few ``import`` naming use cases come to mind:

1. IF no template used THEN append base name to file name (default)
```
[datetime: 2017-11-05 23:43:10] [base name]
[datetime: 2017-11-05 23:43:10] [base name]
[datetime: 2017-11-05 23:43:10] [base name]
```

2. IF template used with no base name AND identical file name exists THEN append hash AND add base name to EXIF
```
[datetime: 2017-11-05 23:43:10]
[datetime: 2017-11-05 23:43:10] [hash]
[datetime: 2017-11-05 23:43:10] [hash]
```

If you can't detect sub-second EXIF, which would be great because then you could append chronological numerics, a UID hash makes most sense to me:

> It's highly unlikely that there is going to be 1,000,000 pictures in one folder all with the same filename generated by elodie
- @jalsin82

If I was that bothered I could manually add numerics to half a dozen sub-second photos (I've only ever managed to take three sub-second photos) 

How does Elodie currently handle duplicates - is it based on hashes?

--

> This begs the question of what to do when the name in EXIF does not match the file name. What's the source of truth and what do we use?
- https://github.com/jmathai/elodie/issues/186#issue-200949649

Good point, usually I feel EXIF should *always* be single source of truth (SSOT) but in the case of Elodie I would use the file name because Elodie focuses on file names

That said, can Elodie leave a revision history in an EXIF field whenever it creates/updates EXIF tags a bit like (I believe) MusicBrainz Picard does; perhaps at a minimum a time stamp and base name - this way if something goes terribly wrong EXIF info can be referenced and rectified manually?

[0] https://github.com/jmathai/elodie/issues/186

Let me know if you have any issues - happy to help

Hope this is useful and to hear back

Regards

**Comment by ldexterldesign** [comment]
> #186 - hmm, it's not clear to me whether we're now storing base names in EXIF on import?:

BUMP

**Comment by jmathai** [comment]
#187 adds the original file name into the EXIF before rewriting it based on the format specified in the configuration file.

**Comment by ldexterldesign** [comment]
Cheers for reply

What's the tag because I'm having trouble seeing it using mac OS Preview - I uploaded a destination image to http://exif.regex.info [o] which does display this but unsure if elodie wrote that tag and/or value?:

<img width="503" alt="screen shot 2018-09-05 at 22 48 40" src="https://user-images.githubusercontent.com/1715809/45120239-dba68b80-b15d-11e8-8700-cf67281c4175.png">

Hope to hear back

Thanks

[o]
![8b1201f1-b907-4400-9388-f79d5e72e2aa](https://user-images.githubusercontent.com/1715809/45120309-04c71c00-b15e-11e8-90a1-0190edaa33ff.png)

**Comment by jmathai** [comment]
It's `XMP:OriginalFileName`. Is this a file you just imported or one which was imported before you pulled down this change? There's also a module that adds this to all of your images but note that it'll update the hash of them all.

**Comment by ldexterldesign** [comment]
> It's XMP:OriginalFileName

Cool, the tag exists then just not showing in macOS Preview - what tool(s) are you using to view image EXIF?

> ... down this change?

Change?

> There's also a module that adds this to all of your images but note that it'll update the hash of them all

Please elaborate?

Yours hopefully

**Comment by jmathai** [comment]
> what tool(s) are you using to view image EXIF?

To validate, I use exiftool as the source of truth but if it's available in preview I'll look there.

> Change?

Was wondering if the photo was imported before you pulled down the commit which started adding the original file name to EXIF.

> Please elaborate

[This commit](https://github.com/jmathai/elodie/commit/15cfe61e034e186e16b0971ab5c25add0cadea26). You should be able to call it using something like `python -m elodie.tools.add_original_name /path/to/library`.

Definitely run some test runs. The ramifications of updating the hash are  applicable if you store hashes elsewhere or if you try to re-import a photo. I need to double-check if it has any bearing on duplicate detection since that's based off a hash (worst case it'll reimport).

The module will update the hash stored by elodie.

**Comment by ldexterldesign** [comment]
> Was wondering if the photo was imported before you pulled down the commit which started adding the original file name to EXIF.

Thought that was what you menat but just checking. I don't know in all honesty. I got half way through processing my files a year ago and just picked the project up again. I have 100GB of images 😣

BTW Are you using another tool to tackle duplicates - I'm liking https://macpaw.com/gemini right now?

> This commit. You should be able to call it using something like python -m elodie.tools.add_original_name /path/to/library.

I'm gonna leave the module for now but thanks

I've been trying to break elodie (i.e. find use cases where I lose a reference to the original file name; non salvageable from file name or EXIF) - do you know of one?

Cheers

**Comment by ldexterldesign** [comment]
> If it doesn't exist I think there should be a way to undo or override all update command options

Add title:

```
// /path/file.jpg
./elodie update --title foo /path/file.jpg
// /path/file-foo.jpg
```

Remove title:

```
// /path/file-foo.jpg
./elodie update --title " " /path/file-foo.jpg
// /path/file.jpg
```

**Comment by jmathai** [comment]
Is this the same issue you were experiencing with #172? IIRC as long as a photo has Original Filename then the title should not be duplicated on reimport.

**Comment by jalsin82** [comment]
I don’t think so.
But I see the value in his request.

In 172, when I had the date/time information as the file name and I imported the file multiple times it would continue to put the date and time stamp appended to the file name, duplicating and triplicating the file name.

--
Jason Alsin
jcalsin@hotmail.com<mailto:jcalsin@hotmail.com>

**Comment by ldexterldesign** [comment]
@jmathai 

> Is this the same issue you were experiencing with #172?

No, I believe https://github.com/jmathai/elodie/issues/172 to be fixed AFAIC

> IIRC as long as a photo has Original Filename then the title should not be duplicated on reimport

Yes, this is the expected behaviour I'm seeing ATM

I'm confused about how `update` and it's options work - what data is updated and where (e.g. EXIF, file name or both)?

Yours hopefully

**Comment by kmajzlik** [comment]
This is must-have for me. I do not want rename of my files.
As i see #225 there should also come change to config.ini-sample (please add there bot Directory and File templates)

**Comment by ldexterldesign** [comment]
@jmathai

BUMP

> I'm confused about how update and it's options work - what data is updated and where (e.g. EXIF, file name, both or something else)?

Yours hopefully

**Comment by jmathai** [comment]
Destination file name is now configurable. Docs are [here](https://github.com/jmathai/elodie#how-file-customization-works). I added a bunch of tests to make sure it's backwards compatible but nothing is better than real world usage to see if there are any bugs. Please try it out.

**Comment by jalsin82** [comment]
Sweet!
It’ll probably be a while. But I’ll test it out when I have some time.

--
Jason Alsin
jcalsin@hotmail.com<mailto:jcalsin@hotmail.com>
