### ISSUE TITLE
Support of Canon Raw CR2 Files

### ISSUE THREAD

**Issue by ahutchison73** [jmathai/elodie#124]
Please evaluate if CR2 files can be supported with the program.  The sample file was too big to attach so I'm going to send it to you in a separate email.

**Comment by jmathai** [comment]
@ahutchison73 cr2 files worked just fine. Merged into master. Thanks for opening the issue.

**Comment by ahutchison73** [comment]
Thanks for the quick response. 

Thanks,
Alden
