### ISSUE TITLE
Process files asynchronously?

### ISSUE THREAD

**Issue by dnwhte** [jmathai/elodie#137]
I don't know much about Python or if it's possible to do async programming in it, but from the code the files seems to be being process synchronously. I have over 150GB of photos and videos to go through and I imagine it's going to take quite a long time especially processing them one at a time. 

Is processing each file asynchronously a possibility? Already being done and I'm not seeing it? Not ideal because of the load on the CPU? Would require too much refactoring? Anyway, just thinking out loud. Thx

**Comment by jmathai** [comment]
It's possible that Python's multiprocess module could be used for this.

https://docs.python.org/2/library/multiprocessing.html

I haven't looked into it but definitely an interesting suggestion.

**Comment by aadee92** [comment]
Hi Jmathai - wanted to say thanks for the great tool. Found it last week when i started a massive photo archive & consolidation project with all my family's old photos scattered across numerous hard disks. Its been great so far, but definitely slow - any progress on this enhancement request? I don't know if you have a feature-bounty program in place, but i'd certainly contribute to this feature if you did. Thanks!

**Comment by jmathai** [comment]
gh-350 achieves 10x-20x improvement in speed. Closing this for now since the changes made by @amaleki should address the underlying issue of it taking a long time.
