### ISSUE TITLE
Call to shutil.copy2 fails on mounted file systems due to copystat

### ISSUE THREAD

**Issue by phifogg** [jmathai/elodie#139]
Hi,

i like the idea of elodie and the way 'she' structured images. Thanks for it.

I am trying to get her to work with the target directory being on a NAS drive. I have therefor embedded the call to elodie on an apple script which would make sure the NAS drive is available prior to starting elodie. So far so good, but somehow she seems to have issues with the NAS.

I tried with 5 images in the incoming folder. Called with standard options nothing will happen. Adding 'allow-duplicates' with target on an empty NAS folder would result in  two files being properly copied. After them she fails with a strange message:

Traceback (most recent call last):
  File "/Users/daniel.draes/Box/elodie/elodie.py", line 235, in <module>
    main()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/Users/daniel.draes/Box/elodie/elodie.py", line 101, in _import
    trash, allow_duplicates)
  File "/Users/daniel.draes/Box/elodie/elodie.py", line 58, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/Users/daniel.draes/Box/elodie/elodie/filesystem.py", line 216, in process_file
    shutil.copy2(_file, dest_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 22] Invalid argument: '/Volumes/Public/Pictures/2015-05-May/Unknown Location/2015-05-22_13-03-19-img_8074.jpg'

Running the same command on a local target directory works without any fault.

Any idea what that could be?

Daniel

**Comment by phifogg** [comment]
Changing fileutil.py line 216 from shutil.copy2 to shutil.copy seems to solve the issue, but obviously, timestamps on the copied file would now differ from local. not too bad as we have the original timestamp in the filename...

My mounted drive is actually an HFS drive mounted via AFP. I would have thought some attributes should be ok to copy :)

**Comment by phifogg** [comment]
As I am new to Python I would greatly appreciate if one of you could have a look at this and see if e.g. os.utime could be used to update the timestamps on the target file after the copy process. It seems to do similar things already in set_date_from_path_video for video files.

**Comment by phifogg** [comment]
Didn't let me sleep... :)

I have forked a version for me and changed filesystem.py to update at least the date of the copied file. Works great so far. Perfect would be to add the hour/minute/sec as well. But not tonight.

Maybe one of you can take this forward now. Thanks!

**Comment by jmathai** [comment]
@phifogg That's odd. I don't think `copy2` would pose an issue for mounted filesystems. Looks like it's the `copystat` which `copy2` does that is causing problems.

From [this StackOverflow thread](http://stackoverflow.com/a/26654245/1318758).

> Let's check copy2 then!
> 
> > Similar to copy(), but metadata is copied as well – in fact, this is just copy() followed by copystat()
>
> So, it's that copystat that is failing - because it can't set the file metadata on such a mount. 

I'll leave this open since you have some other suggestions that might work okay. Let me think about it some and get back to you about incorporating it.

**Comment by phifogg** [comment]
Thanks, I am just about to push another change which will add hours, minutes and seconds.
