### ISSUE TITLE
Add country to folder name?

### ISSUE THREAD

**Issue by edent** [jmathai/elodie#161]
I have photos which I've taken in Rochester, New York - and in Rochester, UK.  Aren't I well travelled ;-)

At the moment, the folder naming is ambiguous.  It simply says "Rochester".  I think it would be handy to have the Country in there as well.

In `geolocation.py`, the function just returns the lowest level of granularity.

```
def place_name(lat, lon):
   ...
    if('address' in geolocation_info):
            address = geolocation_info['address']
            if('city' in address):
                lookup_place_name = address['city']
            elif('state' in address):
                lookup_place_name = address['state']
            elif('country' in address):
                lookup_place_name = address['country']
```

Would it make sense to have a (configurable) output like "Rochester, New York, USA" and "Rochester, England"?

```
    if('address' in geolocation_info):
            address = geolocation_info['address']
            if('city' in address):
                lookup_place_name = address['city']
            elif('state' in address):
                lookup_place_name += "," + address['state']
            elif('country' in address):
                lookup_place_name += "," + address['country']
```

(Obviously needs to be more complex - otherwise you could end up with a folder called ", UK")

**Comment by edent** [comment]
This seems to work quite well.

    if(geolocation_info is not None):
        if('address' in geolocation_info):
            address = geolocation_info['address']
            address_list =[]
            if('city' in address):
                address_list.append(address['city'])
            if('state' in address):
                address_list.append(address['state'])
            if('country' in address):
                address_list.append(address['country'])
            lookup_place_name =  ", ".join(address_list)

It will spit out `Glasgow City, Scotland, UK` if it knows down to the city level, or just `Scotland, UK` if it doesn't know the city, or `UK` if it is country level.  Let's ignore the constitutional question of whether Scotland is a state or a country for computing purposes :-) :gb: 

Are there any problems with that for the rest of the app?

**Comment by jmathai** [comment]
Related to gh-5

**Comment by jmathai** [comment]
Merged and documented at https://github.com/jmathai/elodie#create-your-own-folder-structure
