### ISSUE TITLE
Import order

### ISSUE THREAD

**Issue by vorg** [jmathai/elodie#168]
How are the directories traversed? It seems completely random (async?). E.g. folders 150726/, 150419/, 150724/ and 150726/ again.  That means if the import crashes (e.g. because of https://github.com/jmathai/elodie/issues/167) i have no idea where to restart

Here is what i see in console logs

```
Importing...
/Photos/150726 Highland - Scotland/DSC_0351.jpg
/Photos/150419 South Downs National Park - Seaford/DSC_0304.jpg
/Photos/150724 Loch Lomond and the Trossachs National Park - Scotland/IMG_0074.jpg
/Photos/150521 Toledo - Madrid/IMG_1823.jpg
/Photos/150522 Parc Guell - Barcelona/IMG_2427.jpg
/Photos/150726 Highland - Scotland/DSC_0489.jpg
/Photos/150713 Twickenham, England - Strafford Road/IMG_9296.jpg
/Photos/150726 Highland - Scotland/DSC_0331.jpg
/Photos/150801 Victoria and Albert Museum - London, England/IMG_9655.jpg
/Photos/150510 Hackney Marshes - London, England/IMG_8355.jpg
/Photos/150522 Parc Guell - Barcelona/IMG_2238.jpg
/Photos/150725 Glenfinnan - Scotland/IMG_9496.jpg
/Photos/150528/IMG_8782.jpg
/Photos/150422 Twickenham, England - Strafford Road/IMG_8132.jpg
...
```

**Comment by jmathai** [comment]
Are you on the latest code from the master branch? This should have been fixed last week in #162/#166. // @misterpipine

**Comment by jmathai** [comment]
We use python's `os.walk` to traverse the directories (from docs, `The list is in arbitrary order.`). If the import crashes you can rerun it and it will skip files it already knows about.

**Comment by vorg** [comment]
Hi, that's what i'm doing although via USB3 with my SSD it still takes about 1s per file. Is that SHA1 calculation that takes so long?

**Comment by jmathai** [comment]
@vorg I can't say for sure. The only way I can think of knowing is to try running some of the photos from your internal HDD. It's possible that the checksum takes time as it has to read in the entire file.

**Comment by jmathai** [comment]
@vorg looks like someone else reported slow file copies. That's being tracked at #173 and there's a few resources available for speeding up file copies in Python.
