### ISSUE TITLE
Add support for passing in directories to the update command

### ISSUE THREAD

**Issue by jalsin82** [jmathai/elodie#178]
Is there a way to do a batch update for all pictures in a single folder similar to how a folder of pictures is imported?
This would be useful to be able to update all pictures in a single date folder and add them all to a single album.
This would also be useful to be able to allow elodie to reorganize pictures that have had their EXIF data updated using a third-party application.

**Comment by jmathai** [comment]
You can pass any number of files or folders to `elodie.py`. If you pass a folder it will update all of the photos in that folder.

```
./elodie.py update --location="Sunnyvale, CA" /path/to/file1.jpg /path/to/file2.jpg

./elodie.py update --location="Sunnyvale, CA" /path/to/folder
```

**Comment by jalsin82** [comment]
![image](https://cloud.githubusercontent.com/assets/24847271/21746604/63b761e2-d510-11e6-9863-431939da7e44.png)

It does not appear to work in Windows.

**Comment by jmathai** [comment]
reopening as a feature request.

Do you mind trying multiple files as arguments? Curious if that works on Windows.

**Comment by jalsin82** [comment]
It does. I've used it.
But I'd like to use a separate program to batch edit EXIF data and then us the elodie.py update command and have all of the pictures get reorganized automatically. I plan to do this with my entire picture collection once I know the feature works. It will not be feasible to type in each picture's file location individually.

**Comment by jmathai** [comment]
> It will not be feasible to type in each picture's file location individually.

Agree. I'll have a look and see what needs to be done to support directories.

**Comment by jmathai** [comment]
@jalsin82 mind checking if #182 works for you in windows?

**Comment by jalsin82** [comment]
[cid:image001.png@01D2692E.FC28A560]

It seems to work as long as you don’t add the trailing “\” .

**Comment by jmathai** [comment]
Merged.
