### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 109: ordinal not in range(128)

### ISSUE THREAD

**Issue by phifogg** [jmathai/elodie#179]
Got this error when moving some files around. Not too sure yet why, will investigate.

Could be duplicate to #167.

**Comment by jmathai** [comment]
@phifogg mind seeing if this fixes your issue? https://github.com/jmathai/elodie/pull/180

**Comment by phifogg** [comment]
Confirmed, this fixes my issue.

**Comment by jmathai** [comment]
Closed by #180
