### ISSUE TITLE
Error: Cannot find module 'ipc'

### ISSUE THREAD

**Issue by bdillahu** [jmathai/elodie#198]
Sorry, but I can't figure out the dependencies for the GUI part...

I'm not a node.js guy, so I'm probably missing the obvious, but there seems to be a lot of different packages available that provide a ipc.on call, but nothing I've tried makes it happy...

Any suggestions?

**Comment by jmathai** [comment]
There's an issue (#143) to update the build documentation to make sure the Readme for the GUI works as expected. I suspect the node dependencies changed before we got around to documenting everything and now `npm install` isn't sufficient. 👎

**Comment by jmathai** [comment]
Closing in favor of #143
