### ISSUE TITLE
Allow more than 2 levels of directories for organization

### ISSUE THREAD

**Issue by rishid** [jmathai/elodie#199]
Add support to allow for multiple levels of directory organization. As of now the code is limited to two levels as defined in full_path in the config file. Also, if --album-from-folder option is set than the second provided directory is stomped on with the album name.

Need support for a config such as:
[Directory]
date_year=%Y
date_month=%m-%b
location=%city
full_path=%date_year/%date_month/%album

Add album, location, city, state as reserved keywords and error out if they are defined in config.

**Comment by jmathai** [comment]
Multiple levels of folders are supported as of now. Albums were meant to squash the leaf folder in the original design. In order to preserve that behavior there would need to be some logic added to the syntax of the `config.ini`. I'm undecided if that's worth the hassle.

One alternative is to follow the route of location and use `Unknown Album` in the case where no album exists in the EXIF. Problem there is that such a small % of photos have an album so there's little value in including that in the folder structure.

**Comment by rishid** [comment]
Very cool, thanks for this. I couldn't figure out based on code or docs if there was a way to keep a directory name or something. e.g. 

> 2017/January/Dads birthday/<images>

I guess this may not be possible with auto tagging feature. I guess my work flow is to take my imports and then move them into "event" folders if applicable. I then would like to run elodie on that folder of events and have it organize them.

**Comment by Prosatanos** [comment]
I also would really like to have the ability to incorporate Albums into the destination folder structure

My vast, sprawling and unmanageable collection is already loosely organized in folders, based on events, and I would really like to keep it that way. Ideally I would like the import process to add to folder as an Album Tag, and organize the destination folders like this.

> /Europe Holiday/Paris
> /Europe Holiday/Rome

Great job so far on Elodie!

**Comment by jmathai** [comment]
Elodie does support albums if you use the default folder path of `yyyy-mm-mmm/album-name`. The command line `import` command also supports an argument of `--album-from-folder` which would do what you're asking of adding the leaf folder name as an album name in the photo's EXIF and also use it as the folder's name.

> /Europe Holiday/Paris

That looks like one album nested within another. I'm not sure how to support that via an EXIF album tag besides having a slash in the album name and converting that into folders. Not sure about supporting that though.

**Comment by Prosatanos** [comment]
Thanks for answering. I should have been a bit clearer! is this possible?

"album-name/location"

**Comment by jmathai** [comment]
It's not possible at the moment. The way it can be added is there's a default value for the album if none exists in EXIF. In the case where a photo doesn't have an EXIF album it would be something like `Unknown Album/location`.

The main concern is that most photos for most people won't have albums and I'm hesitant to settle on `Unknown Album` folders all over the place.

Let me think about it a bit more. There's a solution somewhere, I just haven't found it yet.

**Comment by Prosatanos** [comment]
Hmmmmm

So how can I use Elodie to both find photos that are missing a GPS tag, yet retain any existing folder structure?

**Comment by jmathai** [comment]
I think what is really needed is a more robust way to define the folder path. This is a generalized approach that would work for this issue and others.

```
full_path=%year/%album|%city
```

The `|` between `%album` and `%city` would be a fallback to use `%city` if `%album` was empty.

It's entirely feasible and I'm always open to pull requests. It usually takes me a few weeks to think of a clean way to do it without adding much complexity.

The code would be in `filesystem.get_folder_path_definition` [source](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L151) or `filesystem.get_folder_path` [source](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L181).

**Comment by rishid** [comment]
Good idea. We could even put a fallback if none of are defined that the user can define in config

` full_path=%year/%album|%city|"Unsorted" `

**Comment by jmathai** [comment]
> full_path=%year/%album|%city|"Unsorted"

👍

**Comment by jmathai** [comment]
Added support for fallback folders as suggested by @rishid. [Documentation available](https://github.com/jmathai/elodie#using-fallback-folders).
