### ISSUE TITLE
Unknown Location stored in location.json

### ISSUE THREAD

**Issue by jeffkruczynski** [jmathai/elodie#203]
When a location is Unknown, it is stored in location.json.
This prevents the location from being correctly named later (e.g. if it was originally Unknown because MapQuest was unavailable at the time the location was stored).
Workaround is to delete location.json before running.

**Comment by ldexterldesign** [comment]
Hey all,

Thanks for software, as always

Hope you're well

Struggling to get location naming working today - is this bug a show stopper in the latest release or should I persevere?

Hope to hear back

Yours faithfully

**Comment by jmathai** [comment]
@ldexterldesign if you're having an issue with "Unknown Location" then you need to remove the file at `~/.elodie/location.json`. The comment you linked to is talking about a different local database file than the location one.

I'm not sure when this bug was introduced but I imagine it's been there for a while.

**Comment by ldexterldesign** [comment]
@jmathai yea, tried that (see above) - sorry, was editing that comment until a few minutes ago - hope you saw it live

**Comment by jmathai** [comment]
Are you saying that you have a photo with geolocation EXIF and it's not being read properly when you import it? That may not be related to this bug which is specifically about an incorrectly cached name of 'Unknown Location' which persists until the location.json file is deleted.

Can you open another issue with the problem you're having and include details and possible a sample photo if you have one?

**Comment by ldexterldesign** [comment]
@jmathai done

Kind regards
