### ISSUE TITLE
Research/fix geolocation

### ISSUE THREAD

**Issue by ldexterldesign** [jmathai/elodie#204]
https://github.com/jmathai/elodie/issues/203
RETHREAD

Hey all,

Is anyone experiencing difficulties generating (geo)location file names?

Sample file(s):

![img_20170311_170536](https://cloud.githubusercontent.com/assets/1715809/24490171/baf32efe-1521-11e7-8218-54cb8fd2546d.jpg)

<img width="1440" alt="screen shot 2017-03-30 at 08 20 20" src="https://cloud.githubusercontent.com/assets/1715809/24490175/bf18859c-1521-11e7-8ff4-958fa92edd58.png">

Hope to hear back

Cheers

**Comment by jmathai** [comment]
It's working for me. What's your output with `debug=True` in `constants.py`?

```
./elodie.py import --destination=/Users/jaisen/Downloads/test /Users/jaisen/Downloads/source/baf32efe-1521-11e7-8218-54cb8fd2546d.jpeg --allow-duplicates
/Users/jaisen/Downloads/source/baf32efe-1521-11e7-8218-54cb8fd2546d.jpeg -> /Users/jaisen/Downloads/test/2017-03-Mar/Mġarr/2017-03-11_11-35-37-baf32efe-1521-11e7-8218-54cb8fd2546d.jpeg
```

**Comment by ldexterldesign** [comment]
<img width="1440" alt="screen shot 2017-03-30 at 09 28 27" src="https://cloud.githubusercontent.com/assets/1715809/24492327/50ffee9c-152b-11e7-9217-db52894621c5.png">

<img width="1440" alt="screen shot 2017-03-30 at 09 28 57" src="https://cloud.githubusercontent.com/assets/1715809/24492328/510c1942-152b-11e7-9473-60335d1fd406.png">

No debug messages by the looks of it?

Cheers

**Comment by jmathai** [comment]
You've set `debug=True` and your mapquest key is correct in your `config.ini` file? Can you confirm if your `location.json` file has an "Unknown Location" value?

**Comment by ldexterldesign** [comment]
<img width="1440" alt="screen shot 2017-03-30 at 09 42 44" src="https://cloud.githubusercontent.com/assets/1715809/24492925/3f3985cc-152d-11e7-8cba-8028b01a38fe.png">

<img width="1440" alt="screen shot 2017-03-30 at 09 42 48" src="https://cloud.githubusercontent.com/assets/1715809/24492930/4133cf68-152d-11e7-9852-e4510d6559e7.png">

(Will revoke that key later)

Cheers

**Comment by ldexterldesign** [comment]
Fixed it

config.ini was in the wrong place

https://github.com/jmathai/elodie#using-openstreetmap-data-from-mapquest - I shan't be so complacent next time and read the instructions every time I install

Hope this is useful to someone else

Apologies

**Comment by jmathai** [comment]
👍 I think config.ini belongs in the root of the repository. The `*.json` files probably do as well.
