### ISSUE TITLE
--trash fails on Synology DSM 6.1

### ISSUE THREAD

**Issue by baffo** [jmathai/elodie#223]
I have Elodie set up on my Synology, since I use it as a hub for all my photos. Everything works fine, except for the --trash command, which exits on first photo with this error stack trace:

```
Traceback (most recent call last):
  File "./elodie.py", line 345, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./elodie.py", line 115, in _import
    trash, allow_duplicates)
  File "./elodie.py", line 68, in import_file
    send2trash(_file)
  File "/usr/lib/python2.7/site-packages/send2trash/plat_other.py", line 136, in send2trash
    path = str(path, sys.getfilesystemencoding())
TypeError: str() takes at most 1 argument (2 given)
```

It seems to me the problem is in the send2trash python package not invoking str() function correctly, however, the package is up to-date with the current version and I'm surprised that I couldn't find anyone with similar issues with the package. So this leaves me to guess that the package might be ok and there is something else going on.

**Comment by jmathai** [comment]
@baffo do you mind running this to see if the tests pass on your Synology?

```
nosetests elodie/tests/elodie_test.py:test_import_file_send_to_trash_true elodie/tests/elodie_test.py:test_import_file_send_to_trash_false
```

Here's my output.
```
..
----------------------------------------------------------------------
Ran 2 tests in 1.365s

OK
```

**Comment by baffo** [comment]
This is what I get;

```
E.
======================================================================
ERROR: elodie.tests.elodie_test.test_import_file_send_to_trash_true
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/volume1/apps/elodie/elodie/tests/elodie_test.py", line 191, in test_import_file_send_to_trash_true
    dest_path1 = elodie.import_file(origin, folder_destination, False, True, False)
  File "/volume1/apps/elodie/elodie.py", line 68, in import_file
    send2trash(_file)
  File "/usr/lib/python2.7/site-packages/send2trash/plat_other.py", line 136, in send2trash
    path = str(path, sys.getfilesystemencoding())
TypeError: str() takes at most 1 argument (2 given)
-------------------- >> begin captured stdout << ---------------------
/tmp/YVMZPDO79A/VSOYU2GMXC/valid.txt -> /tmp/X4MP1NLKN6/N3E84UQYQW/2016/April/London, UK/2016-04-07_11-15-26-valid-sample-title.txt

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
root: INFO: Writing grammar tables to /usr/lib/python2.7/lib2to3/Grammar2.7.12.final.0.pickle
root: INFO: Writing failed:[Errno 13] Permission denied: '/usr/lib/python2.7/lib2to3/Grammar2.7.12.final.0.pickle'
root: INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
root: INFO: Writing grammar tables to /usr/lib/python2.7/lib2to3/PatternGrammar2.7.12.final.0.pickle
root: INFO: Writing failed:[Errno 13] Permission denied: '/usr/lib/python2.7/lib2to3/PatternGrammar2.7.12.final.0.pickle'
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): open.mapquestapi.com
requests.packages.urllib3.connectionpool: DEBUG: "GET /nominatim/v1/reverse.php?lat=51.521435&lon=0.162714&key=69x3Of2PhXmIbDik06fsJR2U04JtibKc&format=json HTTP/1.1" 200 None
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 1.089s

FAILED (errors=1)
```

**Comment by jmathai** [comment]
Firstly, are you able to patch send2trash's `plat_other.py` on line 136? If that fixes it then we can submit a PR for send2trash.

```
str(path).encode(sys.getfilesystemencoding())
```

**Comment by baffo** [comment]
I patched the `plat_other.py` with your changes and reran the tests:

```
..
----------------------------------------------------------------------
Ran 2 tests in 1.191s

OK
```

This solves it. Thank you for the help! I created a PR with the patch and referenced you and this issue: https://github.com/hsoft/send2trash/pull/11

**Comment by jmathai** [comment]
Awesome. Hopefully the PR is merged and others will not run into the same error you did.

Thanks for opening the issue and submitting the PR.

**Comment by muxketeer** [comment]
I recently experienced this exact same problem. 
I'm currently getting around the issue by overriding plat_other.py, in the docker environment,, with a plat_other.py that includes the change [indicated above](https://github.com/jmathai/elodie/issues/223#issuecomment-305315654).
I.E. Now I'm running the docker image with:

```
sudo docker run -it --rm --name="elodie_me" \
-v /testSourceDirectory/:/media \
-v /testDestination/:/mnt/photoCollection \
-v /etc/localtime:/etc/localtime:ro \
-v /home/jared/dockerfiles/elodie/overrideFiles/config.ini:/root/.elodie/config.ini \
-v /home/jared/dockerfiles/elodie/overrideFiles/plat_other.py:/usr/local/lib/python2.7/dist-packages/send2trash/plat_other.py \
elodie:latest

```
So, whatever change the creators of send2trash implemented, seems to not currently fix the issue here at this time. That, or the plat_other.py that is included in the docker image remains an older version somehow. 

Is there a way to ensure we're getting the latest version of plat_other.py within the docker image?

**Comment by jmathai** [comment]
> I'm currently getting around the issue by overriding plat_other.py, in the docker environment,, with a plat_other.py that includes the change https://github.com/jmathai/elodie/issues/223#issuecomment-305315654.

@muxketeer this implies that the docker image is not getting the fix. Do you know what version of send2trash is being installed?

**Comment by muxketeer** [comment]
@jmathai I'm not sure how to check that version number. Happy to check, just not sure how.
My environment is built using the Dockerfile from within this repo.
However, I assume it's the same version of send2trash that was being used when the issue was originally encountered [up here](https://github.com/jmathai/elodie/issues/223#issue-232469823), as the error message I was encountering today precisely matched what was shown there.

**Comment by jmathai** [comment]
@muxketeer I don't personally run this in a container via the docker image but I'll have a look. Does it persist for you even with `debian:stretch`?

**Comment by muxketeer** [comment]
@jmathai Yes, it persists in `debian:stretch`.
