### ISSUE TITLE
After installing pip

### ISSUE THREAD

**Issue by MacAdda** [jmathai/elodie#23]
I am at this stage:
pip install LatLon
I am at the root of my Mac, but have this error: 
running install_lib
    creating /Library/Python/2.7/site-packages/pyproj
    error: could not create '/Library/Python/2.7/site-packages/pyproj': Permission denied

Thanks for your help :)

Johan

**Comment by patricksan** [comment]
I got the same but was because my brew installed Python incorrectly. 

It was related to new security in the El Captain. 

If that is the case, check how to fix brew on Mac OS El Captain.

**Comment by MacAdda** [comment]
Ok, I found it:
use this on your root mac
sudo chown -R $USER /Library/Python/2.7
