### ISSUE TITLE
Timestamps of source set instead of destination as intended

### ISSUE THREAD

**Issue by adamcandy** [jmathai/elodie#237]
Elodie, by default you copy my photos, but it looks like you then adjust the timestamps of the source not destination files!  Please do not adjust my source files, I would like these left untouched!

The function `process_file()` of `elodie/filesystem.py` applies `os.utime()` (via `set_utime()`, line 386) to the source file (determined from `media`), when it should be applied to the destination path stored in `dest_path`.

**Comment by jmathai** [comment]
That's a bad bug and I'm surprised it hadn't been caught by others or by the tests.

Thanks for catching it. How did you notice it?

**Comment by adamcandy** [comment]
I agree, this is a little bit of a bad bug, but in most cases the information is also in the EXIF metadata which can be used to restore the file timestamp.  For older photos and data formats the file timestamp could be the only way of dating the data and it would be a shame to lose this.

When it comes to years of photos, I'm hesitant to unleash something new without some careful testing!
I have something similar to elodie based on exiftool, so am a little familiar with the challenges and issues.  Elodie goes further and I like the integration, so am looking at this seriously -- it's a nice project.  Thank you for sharing, and for the quick reply.

I have updated the fix in light of your suggestions, so hopefully this issue can be now closed.

**Comment by adamcandy** [comment]
A further comment is that the timestamp handling could be improved, since multiple applications of Elodie to a photo can result in different file timestamps.  The differences I have seen appear due to the differing ways DST is handled (well appear in internal time variables, since there is no explicit handling of DST).  Timezone could also potentially be affecting this (particularly because I am coincidently in a +1 UTC zone).

This has required some thought, and I have a fix which I think gives reasonable behaviour -- and importantly is consistent, whichever way Elodie is called.  I am happy to share and will put together a pull request for comments / merging.

**Comment by jmathai** [comment]
Thanks! It might be a couple days before I can get to merge this.
