### ISSUE TITLE
import pyexiv2

### ISSUE THREAD

**Issue by MacAdda** [jmathai/elodie#25]
Hi again,

I have this error:
./elodie.py", line 4, in <module>
    import pyexiv2
ImportError: No module named pyexiv2

But everything is well installed.(pyexiv2-0.3.2_1 already installed)

Thanks

**Comment by jmathai** [comment]
@MacAdda Do you mind running these commands and letting me know if that fixes it?

```
brew uninstall pyexiv2
brew update
brew install pyexiv2
```

**Comment by MacAdda** [comment]
Fixed but now elodie is doing nothing.
at the root of elodie file I use this:
/elodie.py import --source=“/Users/ja/Pictures/Masters” --destination=“/Users/ja/Dropbox/L_J_Photos/Organised“
Did I miss something?

**Comment by patricksan** [comment]
I would remove the .elodie folder in your home folder.
This will reset the previous configuration of folders

**Comment by MacAdda** [comment]
ok. I have this now:
-bash: elodie.py: command not found

**Comment by patricksan** [comment]
I think you deleted the wrong folder/file.
it is the folder /Users/ja/.elodie

**Comment by MacAdda** [comment]
File "/Users/ja/elodie/elodie.py", line 13, in <module>
    from elodie import arguments
ImportError: cannot import name arguments

**Comment by jmathai** [comment]
@MacAdda I suggest cloning the repo again and starting over once you run the `brew` commands.

Then paste the command and output and we should be able to help.

**Comment by jmathai** [comment]
Closing for now. @MacAdda please reopen if you still have problems.

**Comment by mikemartin** [comment]
@MacAdda  Just spent a couple hours troubleshooting this same issue and I finally realized that once `pyexiv2` installed I received the `sys.path` message below. Once I ran the `site packages` lines, all was fixed.

```
Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/mike/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' 
```

**Comment by ldexterldesign** [comment]
FYI https://github.com/jmathai/elodie/issues/102?_pjax=%23js-repo-pjax-container#issuecomment-341279969
