### ISSUE TITLE
Queens site down?

### ISSUE THREAD

**Issue by jevy** [jmathai/elodie#250]
```https://www.sno.phy.queensu.ca/~phil/exiftool/install.html```

Looks like it's down. I'm trying to figure out if it's been moved somewhere with no luck.

**Comment by jevy** [comment]
Tried to email Phil but it bounced..

**Comment by jmathai** [comment]
Fixed :) http://u88.n24.queensu.ca/exiftool/forum/index.php/topic,8564.0.html
