### ISSUE TITLE
Retrieve camera model

### ISSUE THREAD

**Issue by jeremaii** [jmathai/elodie#254]
Hi all,
I've been trying to adapt this tool to my own workflow and I'm having trouble to retrieve more information from the EXIF. So the question is, if we need to pull more data such as lens info etc... what is the best way to do this and where is it located in the code?

For example, I would like the naming convention to include my camera model. This way I can differentiate what is taken from my gopro versus DSLR. 

Thanks a lot for your help.

**Comment by jmathai** [comment]
I created #255 that adds support for adding the make and model as part of the folder structure. It's not ready to merge but it works. You'll probably want to provide fallback options if make or model are not in the EXIF.

The [test I added](https://github.com/jmathai/elodie/pull/255/files#diff-d2de6d320f1b7278ef0d36c1418bfc2cR233) used this for the directory structure.

```
[Directory]
full_path=%camera_make/%camera_model
```

**Comment by jmathai** [comment]
I added tests, merged and closed in #255.
