### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by eiriktorheim** [jmathai/elodie#256]
I am not able to configure the config file as I want with customized directories. Any idea why? This is what I do.

```
[MapQuest]
key=somekeyhere

[Directory]
location=%city, %state
month=%B
year=%Y
full_path=%year/%month/%location
# -> 2015/December/Sunnyvale, California

```

Expected output: 
2015/December/Sunnyvale, California

Actual output: 
Default directory structure

The config.ini file with the code above is located under the subfolder elodie.

**Comment by eiriktorheim** [comment]
I love the tool by the way!!

**Comment by eiriktorheim** [comment]
What should I write if I want the output to be organized in a year folder, and a month folder under with the filename as in the default. 

Example:
2016/04 April/2016-04-29_20-12-46-default-filename.jpg

**Comment by jmathai** [comment]
The config file needs to be placed at `~/.elodie/config.ini`. The sample `config.ini` you included looks correct and I verified that it produces the output you're looking for.

I'm not sure what you mean by default file name. Can you explain?

**Comment by jmathai** [comment]
I'm closing this for now but feel free to reopen if you continue having the problem.

**Comment by LucaMoiana** [comment]
Hi, I'm having a similar issue, I created this new config.ini file in /elodie (same direcoty as config.ini-sample):

```
[MapQuest]
key=somekeyhere

[Directory]
month=%B
year=%Y
full_path=%year/%month/
# -> 2015/December/
```
and I always get this:

2003-01-Jan/Unknown Location/2003-0111_14_42_44_photo.jpg

but ain't working, what I'm I missing?
I don't have a Mpaquest API

**Comment by LucaMoiana** [comment]
still have the same problem.
I have to mention I moved elodie to my Applications folder so the path for config.ini is:
/Applications/elodie/elodie/config.ini
