### ISSUE TITLE
Import freezing on first photo waiting for exiftool

### ISSUE THREAD

**Issue by mcktrtl** [jmathai/elodie#257]
- Windows 10
- Installed Exiftool using the binary
- Python3

I had this same error through PowerShell as well as Bash/Ubuntu on Windows.

I did some simple print debugging and saw that the code was entering this loop: https://github.com/jmathai/elodie/blob/master/elodie/external/pyexiftool.py#L280 , reading the output, but never exiting the loop. I inspected the output and noticed that the sentinel value coming back from exiftool was: `{ready-}` rather than `{ready}` as defined in https://github.com/jmathai/elodie/blob/master/elodie/external/pyexiftool.py#L82

Updating this line worked for me, locally. No idea why my version is using a different sentinel value.

**Comment by jmathai** [comment]
Submit a PR and if all the tests pass I'll merge :)

**Comment by mcktrtl** [comment]
Sorry, not familiar enough with exiftool to understand why and not really interested in diving deeper. Don't know why the sentinel value is different on my computer -- version, windows, etc., but figured I'd post for anyone else.

Immediately after this I was unable to rename files but couldn't get geolocation to work so I just removed. Best of luck.

**Comment by jmathai** [comment]
Okay. Thanks for reporting. Hopefully it helps someone else in the future.
