### ISSUE TITLE
unit test: restore_dbs() not called if test errors, subsequent tests error

### ISSUE THREAD

**Issue by TonyWhitley** [jmathai/elodie#260]
If reset_dbs() is called and the test errors restore_dbs() is not called.  On Windows this leads to an error the next time they're called because ~/hash.json-test and ~/location.json-test still exist.

See https://github.com/TonyWhitley/elodie/blob/master/elodie/tests/helper.py for fixes.

**Comment by jmathai** [comment]
Can you submit a PR for this? Let me know if you have questions on how to submit one for this the commit you have to fix the tests.

**Comment by TonyWhitley** [comment]
I tried but as a newcomer to git/github I don't have the "git-fu" to do it successfully.

**Comment by jmathai** [comment]
No worries. I created PR #263 but it looks like [the tests fail](https://travis-ci.org/jmathai/elodie/jobs/312299529) since python 2.7 does not support `os.replace`. I added a `_rename` function to the compatability (incorrectly spelled, I know) module.

Here's the steps I did to cherry pick just a single commit.

```
# you don't need to do the following
# I do them since I have to cherry-pick a commit from your fork
git remote add tonywhitely https://github.com/TonyWhitley/elodie.git
git fetch tonywhitely

# branch off my master
# you could do it by adding my fork as your remote instead of what i did above
# ## git remote add jmathai https://github.com/jmathai/elodie.git
# ## git fetch jmathai
git checkout -b restore_dbs_enhancement
git cherry-pick 62818c6e81217a5e4eb6c159bdabbcc77db141bd
git push origin restore_dbs_enhancement
```

**Comment by jmathai** [comment]
Merged. Thanks!
