### ISSUE TITLE
Rearrange library

### ISSUE THREAD

**Issue by navaneeth** [jmathai/elodie#262]
I have asked elodie to keep the directories like `year/month/album`. Now I have changed `config.ini` to `year/album`. 

`elodie.py update` requires either `album` or `location` or other fields to be set. Is there a single command which will reorganize the library according to the new directory structure? 

Also is better for elodie to have a `source` directory specified in the `config.ini`, so that it need not be passed in the command line always.

**Comment by jmathai** [comment]
There's no option to _reorganize_ your photos into a new folder structure. But you should be able to import them to a new destination and they should be organized with the new folder structure there.

Let me know how that goes as I have not tested this in bulk but there were several code changes specifically aimed at making sure this works.

```
elodie.py import --destination=/path/of/a/new/folder /path/to/existing/organized/photos
```

**Comment by navaneeth** [comment]
It worked. But I had to add `allow-duplicates` for it to work.

**Comment by jmathai** [comment]
@navaneeth that makes sense. I should have mentioned that you should delete `~/.elodie/hash.json` which is what keeps track of duplicates.

Amazing that it worked :).
