### ISSUE TITLE
helper.py:reset_dbs() clobbers location.json backup if prior test doesn't clean up.

### ISSUE THREAD

**Issue by kramanathan01** [jmathai/elodie#264]
If a prior test run aborts, a subsequent reset_dbs() will copy the left over test location db over to the good backed up location db. This is due to a bug introduced with the recent commit: 8950f756fe03774d8a34e6fd997372328c056438 for Issue #260 / #263 .

Side effect 1:
Steps to reproduce:
(1) touch ~/.elodie/location.json
(2) Create ~/.elodie/location.json-test with some content:
[{"lat": 51.521435, "name": {"default": "London", "city": "London", "state": "England", "country": "UK"}, "long": 0.162714}, {"lat": 29.758938, "name": {"default": "Houston", "city": "Houston", "state": "Texas", "country": "United States of America"}, "long": -95.3677}, {"lat": 38.1893, "name": {"default": "California", "country": "United States of America", "state": "California"}, "long": -119.9558}]%
(3) run "nosetests elodie_test.py:<<<any import test>>>"
(4) There will be no location.json-test and location.json will be 0 bytes

Side effect 2: Benign, but running test alters state
(1) Create a valid  ~/.elodie/location.json
(2) Ensure there is no ~/.elodie/location.json-test
(3) run "nosetests elodie_test.py"
(4) check ~/.elodie/location.json - Locations from the test (London, Houston and California) will be added to location.json

Suggested fix:
Line 163 of helper.py (reset_dbs()) should change 
From:  if os.path.isfile(location_db): 
To: if not os.path.isfile(location_db):

The value of location_db in line 163 will be location.json-test.
Case 1: If the prior tests failed, line 163 will evaluate to TRUE and the test location.json will be renamed to location.json-test, thus destroying the backed up location.json from a prior good run. os.rename() silently renames even if the destination file exists.
Case 2: If the prior tests ran successfully, line 163 will evaluate to FALSE and execution will skip the block that backs up location.json and return to caller. The import portion of the test in elodie_test.py will execute and just add the test locations to the json file. 

I have made the change, tested manually and pushed the change to my fork. Since this is a simple change, not submitting it as PR.

**Comment by jmathai** [comment]
Fixed by aa12ffb.
