### ISSUE TITLE
Love the concept, but what about hard drive space?

### ISSUE THREAD

**Issue by jacobgraf** [jmathai/elodie#273]
First off, I love the workflow you've created. The only question I have is, how do you handle hard drive space on your Mac? For example, I have a 512GB SSD in my MacBook Pro and there is no way that's big enough to store my whole photo library but from what I understand about your diagram/workflow, that's where all the files live, or am I missing something?

**Comment by jacobgraf** [comment]
All of that makes sense. Stream is only for G Suite though I believe. Hmm. The other solutions definitely sounds like a pain too. Poop.

**Comment by jmathai** [comment]
I also tried it with Bittorent sync which sounded like it had a lot of promise but the implementation did not work and was really confusing.

There's also Dropbox Smart Sync but it's also for Professional and Business accounts.
