### ISSUE TITLE
Combine Date and Album Names in one folder name

### ISSUE THREAD

**Issue by QasimK** [jmathai/elodie#279]
I really like the concept behind Elodie, I think it is just the perfect solution to actually managing your photo library in a way that is cross-platform and future-proof. In particular, using EXIF and (very simple) folder structures should play more nicely with other tools that any SQLite database would.

I was trying to combine the date and album/location names into one folder. For example, `2018-08 Holiday` rather than `2018-08/Holiday`.

I would like to do this because I want to be able to see my different albums at a glance when I am browsing my photos library, so that I can more easily reminisce (or something like that). Another reason for this is if I have an album (or location) that is across multiple months I can more easily identify it. For example, all "Home" photos for the entire year could probably just be lumped into one folder.

So instead of (2 albums and 3 locations in this example):

```
2018-08/
    Holiday
    Conference
    London
    New York
    Unknown Location
```

It would be:

```
2018-08 Holiday/
2018-08 Conference/
2018-08 London/
2018-08 New York/
2018-08 Unknown Location/
```

I spent about an hour working the `config.ini`, and then having a look at the source code, before determining that Elodie does not currently support this. I'm not entirely sure how well this would work in practice (too many folders?), so if anyone thinks this is a bad idea please let me know.

Would this be incompatible with Elodie in any way, or require significant work outside of just `filesystem.py`?

**Comment by jmathai** [comment]
I assume you meant you would like the following folder structure with spaces.

```
2018-08 Holiday/
2018-08 Conference/
2018-08 London/
2018-08 New York/
2018-08 Unknown Location/
```

Does the following work?

```
month=%m
year=%Y
full_path=%year-%month %city
```

**Comment by QasimK** [comment]
That's right, that is what I meant - I've fixed the original post as well.

Using your configuration, I get the following error:

```
me@me-desktop ~/> python ~/Projects/oss/elodie/elodie.py import --debug --source '/home/me/example/first' --destination '/home/me/example/second'
Traceback (most recent call last):
  File "/home/me/Projects/oss/elodie/elodie.py", line 345, in <module>
    main()
  File "/home/me/.local/share/virtualenvs/elodie-NDMq10dE/lib/python3.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/me/.local/share/virtualenvs/elodie-NDMq10dE/lib/python3.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/me/.local/share/virtualenvs/elodie-NDMq10dE/lib/python3.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/me/.local/share/virtualenvs/elodie-NDMq10dE/lib/python3.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/me/.local/share/virtualenvs/elodie-NDMq10dE/lib/python3.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/me/Projects/oss/elodie/elodie.py", line 115, in _import
    trash, allow_duplicates)
  File "/home/me/Projects/oss/elodie/elodie.py", line 64, in import_file
    media, allowDuplicate=allow_duplicates, move=False)
  File "/home/me/Projects/oss/elodie/elodie/filesystem.py", line 339, in process_file
    directory_name = self.get_folder_path(metadata)
  File "/home/me/Projects/oss/elodie/elodie/filesystem.py", line 261, in get_folder_path
    return os.path.join(*path)
TypeError: join() missing 1 required positional argument: 'a'
```

**Comment by ldexterldesign** [comment]
> You can construct your folder structure using a combination of the location, dates and camera make/model. Under the Directory section of your config.ini file you can define placeholder names and assign each a value. For example, date=%Y-%m would create a date placeholder with a value of YYYY-MM which would be filled in with the date from the EXIF on the photo.
https://github.com/jmathai/elodie#how-folder-customization-works

IMO `[Directory]` would do with being in the README code examples - I had to come to this issue to fix my config.ini syntax

Hope this is useful

Regards

**Comment by ldexterldesign** [comment]
Similarly, I want the following structure?:

```
[Directory]
date=%Y-%m
device=%camera_make - %camera_model
location=%country - %state - %city
full_path=%date/%device|"Unknown device"/%location
```

What's the reason `location` works but `device` doesn't - is it because "complex placeholders" are hardcoded?:

If yes, can we introduce variables so users can make up their own complex placeholders

If no, can we simply get this `device` complex placeholder added

Yours hopefully

**Comment by jmathai** [comment]
I had a look at the code. Mixing date and location in a single folder name is not supported but [this is the function](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L218) to which handles this logic. Not trivial but a good exercise if you're up for a challenge or want to really understand how the parsing works :).

Supporting device is a bit more straightforward. This diff should get what you're asking for to work. I'm happy to add support for this but would prefer to make it a bit more generic so it would work across all supported EXIF fields in `meta_data`.

```diff
diff --git a/elodie/filesystem.py b/elodie/filesystem.py
index 6c5d83e..7958559 100644
--- a/elodie/filesystem.py
+++ b/elodie/filesystem.py
@@ -251,6 +251,13 @@ class FileSystem(object):
                     )
                     path.append(parsed_folder_name)
                     break
+                elif part in ('device'):
+                    custom_parts = re.findall('(%[a-z_]+)', mask)
+                    folder = mask
+                    for i in custom_parts:
+                        folder = folder.replace(i, metadata[i[1:]])
+                    path.append(folder)
+                    break
                 elif part in ('album', 'camera_make', 'camera_model'):
                     if metadata[part]:
                         path.append(metadata[part])
```

**Comment by jmathai** [comment]
Curiosity got the better of me. #283 adds support for a `%custom` placeholder. It definitely breaks fallback folders though so your initial request to include `Unknown Location` will not work (and the failing tests are proof).

The PR has 4 tasks which need to be completed before merging.

**Comment by ldexterldesign** [comment]
Hey @jmathai,

Thanks for enhancement

> I'm happy to add support for this but would prefer to make it a bit more generic so it would work across all supported EXIF fields in meta_data

Yes, that would be great and I'm more than happy to wait for that - I've subscribed to the PR

BTW where can I find documentation on the ``meta_data`` fields, do you mean ``metadata``?

Hope to hear back

Keep up great work!

Cheers

**Comment by ldexterldesign** [comment]
BUMP

**Comment by jmathai** [comment]
Metadata is defined [here](https://github.com/jmathai/elodie/blob/master/elodie/media/base.py#L92)[1].

[1] https://github.com/jmathai/elodie/blob/master/elodie/media/base.py#L92

**Comment by jmathai** [comment]
FYI #283 was merged which adds support for date and album to be used in the folder name.

**Comment by ldexterldesign** [comment]
https://github.com/jmathai/elodie/pull/283#issuecomment-477857782 - visibility
