### ISSUE TITLE
How to capitalize filename?

### ISSUE THREAD

**Issue by muff1nman** [jmathai/elodie#312]
I'd like to captialize my filenames. Here is my current configuration:

```
[Directory]
year=%Y
month=%m
day=%d
full_path=%year/%month/%day

[File]
name=%original_name.%extension
```

Is there a way I can capitalize my file names without the following patch?

```
diff --git a/elodie/filesystem.py b/elodie/filesystem.py
index 5048b78..dc272a5 100644
--- a/elodie/filesystem.py
+++ b/elodie/filesystem.py
@@ -211,7 +211,7 @@ class FileSystem(object):
                     name,
                 )
 
-        return name.lower()
+        return name.upper()
 
     def get_file_name_definition(self):
         """Returns a list of folder definitions.
```

**Comment by jmathai** [comment]
There's no way to capitalize file names but your patch would do the trick. If you'd like to include a PR which adds a `case` value under `[File]` in the config then reopen this issue and submit the PR so I can look to merge it. That way your branch will cleanly merge with this as a remote.
