### ISSUE TITLE
Google Photos Sync Going Away

### ISSUE THREAD

**Issue by jevy** [jmathai/elodie#315]
Hey @jmathai! It looks like the Google Drive -> Google Photos sync [is going away](https://support.google.com/photos/answer/9316089). This was part of your workflow right? Have you thought about if what you're going to do as an alternative?

**Comment by jmathai** [comment]
Hi @jevy - you're correct that the Google Drive -> Google Photos really throws a wrench in my workflow. I've been looking at a few alternatives (iCloud Drive + iCloud Photos, Synology Drive + Synology Moments) but none work for my specific needs.

That being said, I believe I found a way to closely mirror my workflow by adding support for Elodie to integrate with Google Photos and I've started a branch with code to do that. I'll keep this issue open to track progress but expect to have something that works in a week or so.

**Comment by jmathai** [comment]
Created #319 to add support for Google Photos.
