### ISSUE TITLE
Enable multiple configurations

### ISSUE THREAD

**Issue by MiguelCatalan** [jmathai/elodie#338]
I am interested in using Elodie for my Synology NAS. But there are multiple users and probably everyone would want custom configurations.

Is there any way to have multiple configurations files for each user?

**Comment by MiguelCatalan** [comment]
If I understand it right, this only works for changing the path of the configuration. Not to have multiple ones.

If I'm wrong, Do you have any doc of example on how to make it work for multiple users?

Thanks in advance. Awesome job in this project.

**Comment by MiguelCatalan** [comment]
btw @jmathai I cannot reopen it, seems like I have not enough permissions.

**Comment by jmathai** [comment]
You can do this directly on the command line or by wrapping this in a shell script. Essentially you need to set an environment variable when running a command such that it points to the appropriate folder for application directory. 

```
export ELODIE_APPLICATION_DIRECTORY=~/.elodie/someuser
./elodie.py import /path/to/source
```

**Comment by MiguelCatalan** [comment]
Oh I see, thanks!
