### ISSUE TITLE
Exclude thumbnail.jpg files in @eaDir on Synology

### ISSUE THREAD

**Issue by gti96** [jmathai/elodie#340]
Is there a way to exclude importing those thumbnail index files in @eaDir of DSM. Using DSM 6.1.

**Comment by jmathai** [comment]
If I recall correctly, there's a `@eadir` folder in every folder with photos.

There's not exclude option supported by elodie but you should be able to do this using standard unix tools.

```
# Sample folder structure
➜  exclude tree
.
├── foobar
│   ├── @eadir
│   │   └── file.jpg
│   └── file.jpg
└── test
    ├── @eadir
    │   └── file1.jpg
    ├── file1.jpg
    └── test2
        ├── @eadir
        │   └── file2.jpg
        └── file2.jpg

# Use find and grep to filter out @eadir files
➜  exclude find . -type file | grep -v '@eadir'
./test/file1.jpg
./test/test2/file2.jpg
./foobar/file.jpg

# Try this command to pass those files to elodie.py
find ./ -type file | grep -v '@eadir' | xargs -I{} /path/to/elodie.py --destination=/path/to/destination
```

**Comment by gti96** [comment]
Thanks for quick response.

`find . -type f | grep -v '@eaDir'`

Above definitely works to skip the files in '@eaDir'.
However when I try

'find ./ -type f | grep -v '@eaDir' | xargs -I{} /path/to/elodie.py --destination=/path/to/destination`

I got 5 times the following

`Error: no such option: --destination`

I believe this is shown 5 times because of the 5 files to be imported in source.
Unfortunately, I cannot work out what it means.

**Comment by jmathai** [comment]
Less fancy.

```
for i in $(find . -type f | grep -v '@eadir'); do ./elodie.py --destination=/path/to/destination $i; done
```

Or expanded for readability.

```
for i in $(find . -type f | grep -v '@eadir'); \
  do ./elodie.py --destination=/path/to/destination $i; \
done
```

**Comment by gti96** [comment]
Just work out that the command is missing 'import' thus the error.
However, now I just keep getting the following response continuously from the input.

```
****** SUMMARY ******
Metric      Count
--------  -------
Success         0
Error           0
****** SUMMARY ******
Metric      Count
--------  -------
Success         0
Error           0
****** SUMMARY ******
Metric      Count
--------  -------
Success         0
Error           0

```

After more thought, I am not sure this is the best method to do it as this is like running elodie.py thousands of times even if it works. 
I think I will look at modifying get_all_files from filesystem.py to do this.

Thanks, jmathai.

**Comment by jmathai** [comment]
Reopening this issue. If you do manage to implement this via an `--exclude` parameter then definitely open a PR.

**Comment by gti96** [comment]
I have implemented it without the `--exclude` parameter now and I can look into doing it with this parameter too. 
Sorry I am new to contributing to github and I try to read about pull request on help.
It says I should create a branch, commit and create PR but I am stuck on creating a branch. It doesn't seem like there is an option for me to create a branch.
Am I missing something? If this is not the way to do it, please point in the right direction.

**Comment by gti96** [comment]
I got the --exclude parameter working now too. just need to know how to submit.

**Comment by jmathai** [comment]
Closed in gh-340 by adding the ability to pass in an `--exclude-regex` parameter or specify an `[Exclusions]` section in the config.
