### ISSUE TITLE
slow (10s/image) on raspberry pi 3, 25k images

### ISSUE THREAD

**Issue by capocasa** [jmathai/elodie#347]
OK so this is one of these vaguely defined and hence hard-to-reproduce bug reports, but I put it in here to document the behavior rather than with an expectation to get this fixed yesterday.

I ran the current master of elodie (75e65901a94e14e6fd1ff7ad7a6e0f1c42edccc4) on a raspberry pi with 4 folders and about 25k images on a raspberry pi. It was about 1 image per second at first, but degenerated until it was about 20 seconds per image at 3000, where I aborted. I am guessing there is some kind of nonlinear performance bottleneck there, but I'm not sure where to start looking. In any case, I would assert that while I did think it's okay to keep elodie running for a couple days on an import that would be fine, however, exponentially degrading performance might mean it won't complete at all, hence the abort. Thanks for reading!

**Comment by QasimK** [comment]
I wouldn't be surprised if this was solely down to the hardware. Raspberry Pis are notorious for their poor I/O, and it is easy to use a not-so-good microSD Card.

**Comment by amaleki** [comment]
I just opened a performance improvement issue which some changes I've made.  It would be great if you could see what kind of results you see on a raspberry pi.

Performance Improvements https://github.com/jmathai/elodie/issues/350

Commit: 
https://github.com/amaleki/elodie/commit/afd576600d7a0ba864b6bb2f93241a00711adb7a#diff-5a2b1bdaf59cbc881a6ad218eaabdc42
Fork: https://github.com/amaleki/elodie

**Comment by evanjt** [comment]
I incorporated your changes on my fork and it worked great amaleki. 

Also I found (in general) that if you're not using --trash, the speed is very slow. I was importing at a speed of about 20,000 images per day vs 8000 per hour after incorporating amaleki's improvement and --trash

Also, if anyone has time, I've made a change to build a local location SQLite DB for location querying removing the need to query MapQuest on my fork: https://github.com/evanjt/elodie/
