### ISSUE TITLE
Location in directory path not working properly

### ISSUE THREAD

**Issue by MiguelCatalan** [jmathai/elodie#359]
I have done several tests before and dived in the issues/PRs in order to see If I was the only one.

### Scenario
Using this config:

```
[Directory]
date=%Y_%m_%d
location=%city
full_path=%date-%location|%date
```
### Expected behavior:
- If a picture has no location information in the EXIF data, the directory should be just the date.
- If a picture has location information in the EXIF data, the directory should contain the name of the city.
![image](https://user-images.githubusercontent.com/3306324/76704028-7595af80-66d6-11ea-8c37-7d42953b9e45.png)

### Current behavior:
- No matter if the picture has a location or not, the directory is just named with the date.
![image](https://user-images.githubusercontent.com/3306324/76704091-e76df900-66d6-11ea-9db0-ac09842cb87e.png)

I checked there was a thread about this issue (https://github.com/jmathai/elodie/issues/279), but it seems the error still present.

**Comment by MiguelCatalan** [comment]
Tell me if I can do anything to help.

**Comment by MiguelCatalan** [comment]
Doing some other tests, if the location is under the main directory, works, but not at the same level.
```
[Directory]
date=%Y_%m_%d
location=%city
full_path=%date/%location|%date
```

![image](https://user-images.githubusercontent.com/3306324/76704443-5c423280-66d9-11ea-9608-ec10e9c2f9f0.png)

**Comment by jmathai** [comment]
Hi @MiguelCatalan - fallback is not supported for multi-variable folders. In your example the folder you're looking to fallback from uses both date and location. I'm not sure if this will work but can you try both of the following?

```
[Directory]
date=%Y_%m_%d
location=%city
custom=%date-%location
full_path=%custom|%date
```

```
[Directory]
location=%city
custom=%Y_%m_%d-%location
full_path=%custom|%date
```
