### ISSUE TITLE
Elodie acts as if PNG files do not exist.

### ISSUE THREAD

**Issue by lreinink** [jmathai/elodie#361]
I've used Elodie to organise my pictures. This included some screenshots I made on my computer, which are in PNG format. I noticed that Elodie acts as if these do not exist. They show up as 0 completed 0 error. Is this intended? What would be the best course of action?

Edit: I just read your blog post and I see that this is indeed intentional, to make sure that no unwanted images from the Downloads folder are imported. What would be the best workaround for this?

**Comment by thetom88** [comment]
May I add that also TIFF and probably DNG file are ignored?

**Comment by jmathai** [comment]
The supported file types are [here](https://github.com/jmathai/elodie/blob/master/elodie/media/photo.py#L31).

* DNGs - supported.
* PNGs and TIFFs - I'm not sure if they contain EXIF but worth double checking. A simple way to check is adding it to the list I linked above.

**Comment by lreinink** [comment]
jmathai, thank you. This worked for me. the PNG files do contain exif, but all locations are unknown. This is to be expected, however.

**Comment by jmathai** [comment]
@lreinink 👍. if you made any changes locally that worked for you then let me know and if it's useful for others it would be great if you could submit a pull request.

**Comment by lreinink** [comment]
I did exactly what you proposed, I changed `extensions = ('arw', 'cr2', 'dng', 'gif', 'heic', 'jpeg', 'jpg', 'nef', 'rw2')` in `photo.py` to `extensions = ('arw', 'cr2', 'dng', 'gif', 'heic', 'jpeg', 'jpg', 'nef', 'rw2', 'png')`
