### ISSUE TITLE
File customization documentation misleading and requires generalization

### ISSUE THREAD

**Issue by adamcandy** [jmathai/elodie#367]
Firstly, great that file customization has made it into the master! Good job.

I had a branch working for this back in 2017, but did not push to get the code into the main repository (see [adamcandy/elodie/tree/arbitrary_filename_timestamp](/adamcandy/elodie/tree/arbitrary_filename_timestamp)).  It even made the full filename lower case like the code now in the main master --  Great all this functionality is now mainstream!

Attempting to use the main repo version of file customization, following the details in the root Readme.md, led to problems.  I found it messed up movies and all files not ending in `.jpg`.

Checking the source, I found the `%extension` keyword available already, so this just needs a simple update to the documentation:

```
[File]
date=%Y-%m-%b-%H-%M-%S
name=%date-%original_name-%title.jpg
```
to
```
[File]
date=%Y-%m-%b-%H-%M-%S
name=%date-%original_name-%title.%extension
```

Pull request to follow shortly.

**Comment by jmathai** [comment]
Unsure why I missed this PR. Thanks and glad it's working - hopefully you're on master now :)
