### ISSUE TITLE
Prefer English names logic is broken

### ISSUE THREAD

**Issue by adamcandy** [jmathai/elodie#369]
`bool` cannot be used to test for a True or False string in python.

In **elodie/geolocation.py**:
```
__PREFER_ENGLISH_NAMES__ = bool(config['MapQuest']['prefer_english_names'])
```
will evaluate to **True** for any string specified!

**Comment by adamcandy** [comment]
Fixed in [PR 370](https://github.com/jmathai/elodie/pull/370).

**Comment by crishnakh** [comment]
Hi, is this bug related to the config prefer_english_names=False ?
Because I set it in the config.ini but the locations names are still cerated in English.

**Comment by adamcandy** [comment]
Yes @crishnakh exactly.  The fix in PR 370 sorts all the problems I had with this option, so give this a try.  I should get around to merging this change in together with some others.  I think @jmathai wanted me to combine the PRs rather than pull in individually.

**Comment by jmathai** [comment]
The new MapQuest API no longer supports this functionality. Have opened #425 to track it but will probably just mark the capability as deprecated.
