### ISSUE TITLE
Updating location not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by shivams** [jmathai/elodie#376]
Updating location does not work on Ubuntu 20.04. I am not sure if it's because of some bug in `exiftool` or `pyexiftool`. However, updating date works fine. E.g. running the following still puts the images in the "Unknown Location" folder:

```shell
elodie.py update --location="Bengaluru" 2015-11-13_15-00-48-img_20151113_203048.jpg
```

I am using the `master` branch of `elodie`, and have tried using Python 3.8, 3.6 and 3.7. But the behavior is the same everywhere.

### UPDATE:
Even when importing images which have the GPS location in their exif metadata, `elodie` puts them in the "Unknown Location" folder.

**Comment by jmathai** [comment]
Have you added a MapQuest API key to your `config.ini` file? Directions are [here](https://github.com/jmathai/elodie#using-openstreetmap-data-from-mapquest).

If you've already done that then run your command with the `--debug` flag and see what MapQuest URL is being called and if it works for you.

Please reopen if you still have issues.

**Comment by shivams** [comment]
Sorry, I had not added the MapQuest API key to the `config.ini`. My bad. It works perfectly now.
