### ISSUE TITLE
Upgrade Pillow to 7.2 to address security vulnerability

### ISSUE THREAD

**Issue by jmathai** [jmathai/elodie#384]
https://github.com/jmathai/elodie/network/alert/requirements.txt/Pillow/open

**Comment by Jogai** [comment]
Maybe enable dependabot: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-and-disabling-version-updates

**Comment by jmathai** [comment]
@Jogai I do have a PR open (gh-385) but the version of Pillow without the vulnerability is not available for Python 2.7.

**Comment by Jogai** [comment]
In that case this issue is a bit premature, because elodie should move to 3 first: https://www.python.org/doc/sunset-python-2/

**Comment by jmathai** [comment]
Closed in #385
