### ISSUE TITLE
Elodie hangs on import | How to generate more output for debugging problem?

### ISSUE THREAD

**Issue by anoduck** [jmathai/elodie#406]
Elodie manages to generate-db fine, but will not run import without hanging. Using the flag `--debug` generates no output, neither does running elodie in idle with the debugger enabled. It may generate a few lines of output when it first encounters valid media files, but once it encounters a valid file it stops cold in its tracks and does not exit with any error code. I have left it running for over 12 hours without any progress.

Due to system restrictions while running OpenBSD, that of being unable to compile pillow due to C libs, I am unable to run Elodie in a virtualenv. Albeit I do have py3-Pillow version 8.2.0 installed. I will test and see if it is running successfully on my linux systems.

**Comment by anoduck** [comment]
I have reverted to using python2.7 instead of python3.9 in hopes of fully matching Elodie's required library versions. From what I see, I have successfully accomplished this, and now possess the required libraries for Elodie matched with the required versions. Yet, Elodie still hangs when attempting to import photos.

How can more output be generated to help debug the issue other than using the obvious `--debug` flag?

**Comment by jmathai** [comment]
All `log.*` lines should be printed when using `--debug`. Here's an [example](https://github.com/jmathai/elodie/blob/master/elodie/filesystem.py#L491).

Code execution when importing photos starts [here](https://github.com/jmathai/elodie/blob/master/elodie.py#L105).

Can you add some `log.info()` lines and post back where it hangs?

**Comment by anoduck** [comment]
Most definitely, kind sir. 
Let me roll up my sleeves and see what I can get into.
