### ISSUE TITLE
ImportError: cannot import name 'Iterable' from 'collections' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by chichicello** [jmathai/elodie#433]
may i know whats going on with it? thanks

**Comment by jmathai** [comment]
This is an issue with Python 3.10. It's being tracked in gh-418.

2 options:
1. Wait for gh-418 to be fixed.
2. Use Python 3.9.
