### ISSUE TITLE
License incompatibility?

### ISSUE THREAD

**Issue by waynew** [jmathai/elodie#44]
It looks like LatLon has a GPL (not LGPL) license: https://pypi.python.org/pypi/LatLon/1.0.2 (see the bottom)

IANAL, but I'm pretty sure that requires software linked to it to be licensed GPL, too?

**Comment by jmathai** [comment]
Thanks for pointing that out. I've put an email in to a couple lawyer friends who specialize in open source licensing.

**Comment by jmathai** [comment]
@waynew Looks like the solution is to omit LatLon from the pip package and instruct the user that they'll need to install it manually. Simply using LatLon isn't a violation but once we package it up we *convey* that Elodie is GPL.

Does pip let you add a message upon successful installation?

**Comment by noonat** [comment]
It looks like we're only using LatLon to convert between degrees/minutes/seconds and decimal degrees, is that right? It might be easier to just do that conversion inline, rather than including the GPL dependency, as the formula is pretty simple for it: http://www.rapidtables.com/convert/number/degrees-minutes-seconds-to-degrees.htm

**Comment by noonat** [comment]
Huh, I see you already have functions for this in the geolocation module! Any reason not to just use those instead? This might also help with some of the precision issues, since it looks like the geolocation code is using Fraction instead float (like LatLon does).

**Comment by jmathai** [comment]
@noonat good point. Looks like we can just swap out usage of `LatLon` with the geolocation module. It will require the tests to be updated though. I'll try to have a look in the next couple days if someone else doesn't get to it before me.

**Comment by jmathai** [comment]
Closed in PR gh-83.
