### ISSUE TITLE
MapQuest API key issues

### ISSUE THREAD

**Issue by edent** [jmathai/elodie#45]
Not strictly a problem with your app - but MapQuest are having issues automating the generation of API keys. 

See the discussion at https://developer.mapquest.com/forum/free-api-key

I've previously had an API key with them, but now the site looks like this:

![mapquest](https://cloud.githubusercontent.com/assets/837136/11997164/362dd12c-aa6c-11e5-999a-5fa66af40012.png)

Wondering if there are any other suitable geo-coding services which are available?  Perhaps http://wiki.openstreetmap.org/wiki/Nominatim ?

**Comment by edent** [comment]
Well, the good news is that because MapQuest is an Nominatim instance, it's possible to do a straight replacement of https://github.com/jmathai/elodie/blob/master/elodie/geolocation.py#L102 with:

`r = requests.get('https://nominatim.openstreetmap.org/reverse?%s' % urllib.urlencode(params))`

(I assume the same is also true for `lookup(name)` but I've not tried it.)

The *bad news* is [Nominatim's usage policy](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy).  Specifically:

> * No heavy uses (an absolute maximum of 1 request per second).
* Provide a valid HTTP Referer or User-Agent identifying the application (stock User-Agents as set by http libraries will not do).

> Bulk Geocoding

> As a general rule, bulk geocoding of larger amounts of data is not encouraged. If you have regular geocoding tasks, please, look into alternatives below. Smaller one-time bulk tasks may be permissible, if these additional rules are followed
> * limit your requests to a single thread
* limited to 1 machine only, no distributed scripts (including multiple Amazon EC2 instances or similar)
* Results must be cached on your side. Clients sending repeatedly the same query may be classified as faulty and blocked.

I'm not entirely sure if this app would fall foul of these rules though.

**Comment by zingo** [comment]
As a mater of fact I'm looking into a cache 
https://github.com/zingo/elodie/commit/d793ce038b5a30de1ff3b26472118375c8471366
It seem to work but need a little cleanup like maybe you would like to set the distance for coordinate lookup reuse currently it's about 3km. And it saves the file to disk everytime an entry is added. Maybe it should not be saved at all? But lets have that discussions in it's own issue. I was planing on working on it a bit more before showing it as I just got i working but as the discussion above mention the need I just wanted to show it.

**Comment by jmathai** [comment]
@edent This link works for me. https://developer.mapquest.com/plan_purchase/steps/business_edition/business_edition_free

Glad that Nominatim can be a drop in replacement. We can make the path configurable. I think this tool tends to fall within their requirements. When doing a mass import the number of calls may be around 1/second but it's also possible to throttle that. Once your initial import is done the remaining usage tends to be much more sparse.

@zingo that is brilliant. I've been wanting to add that in almost the same way you have. I would probably move it to the `geolocation` module though. I'll create an issue for this and you can open a pull request once you're done :).

**Comment by edent** [comment]
@jmathai thanks - the MapQuest site now seems to be working again :-)

**Comment by ldexterldesign** [comment]
👋 https://github.com/jmathai/elodie/issues/258#issuecomment-603589476
