### ISSUE TITLE
config.ini ignored

### ISSUE THREAD

**Issue by LorisSchmit** [jmathai/elodie#459]
Hi, for some reason my config.ini file is being ignored. I tried adding different configs like the format of the output directory or the Google Photos Plugin, but no change seems to have an effect.
I installed elodie in an conda environment, maybe that is causing issues? After I renamed the **config.ini-sample** to **config.ini** and left it there in the elodie directory.

What could cause this? Running `/.elodie.py import` works perfectly.

Thanks for your help!

**Comment by jmathai** [comment]
Can you share more information about your directory structure and where your `config.ini` file is located as well as the contents of `config.ini` (removing any sensitive information)?

**Comment by LorisSchmit** [comment]
I figured it out, I didn't install elodie in my home directory and I didn't define the environment variable `ELODIE_APPLICATION_DIRECTORY`. The `config.ini` is detected now, however I still have a problem with the Google Photos plugin. When I run `/.elodie.py batch --debug` the output is `Called batch() for GooglePhotos` but my browser does not open and there is also no API call in the Google cloud console. While creating the OAuth client ID in the Google Cloud Console, there wasn't an **other** for the application type so I chose **Desktop app**, not sure if this is an issue?

This is the content of my config.ini:
```
[Directory]
location=%city, %state
month=%m
year=%Y
full_path=%year/%month

[Plugins]
plugins=GooglePhotos
 
[PluginGooglePhotos]
secrets_file=/full/path/to/my/home/src/elodie/client_secret.json
auth_file=/full/path/to/my/home/src/elodie/credentials/auth_file.json
```

**Comment by LorisSchmit** [comment]
Now the debug output when running `./elodie.py batch --debug`is:

```
{"GooglePhotos": "Could not initialize session"}
{"GooglePhotos": "/path/to/image failed to upload."}
Called batch() for GooglePhotos
```

**Comment by jmathai** [comment]
You may need to add some log messages in https://github.com/jmathai/elodie/blob/master/elodie/plugins/googlephotos/googlephotos.py.

The message `Could not initialize session` is from the google photos library which would seem to indicate that it's somewhere in `set_session()`.

**Comment by LorisSchmit** [comment]
I figured it out! I hadn't properly defined the location of the secret file... Everything works perfectly now. Thanks for the hints and kudos for the good work!
