### ISSUE TITLE
Cache location names and return them when looking up coordinates

### ISSUE THREAD

**Issue by jmathai** [jmathai/elodie#52]
gh-47 by @zingo added caching for location coordinates. We can leverage the same cache to lookup a name and return its corresponding name.

In addition to a performance boost this lets us further customize location labels and folders as a result. If the location db contains a `name`, `lat`, `long` set you can update a set of photos with that name. That means you can explicitly set labels and use `./elodie.py update --location="Home" /path/to/file.jpg` which would assign it the exact location from the cache and place the photo(s) into a folder named `Home` instead of the normal "city name".

```
{"lat": 39.387227, "name": "Home", "long": -115.026129}
```

TODO: We need to come up with a way to backup/store the databases/caches that we're storing.

**Comment by ibizaman** [comment]
This is great, thanks!
