### ISSUE TITLE
Folder created with update command get misnamed

### ISSUE THREAD

**Issue by Kraymer** [jmathai/elodie#54]
Some UTC problem ?

```
./elodie.py update --time="2010-05-01" /Users/flap/Pictures/elodie/2004-12-Dec/Unknown\ Location/2004-12-31_23-0*
{"source":"/Users/flap/Pictures/elodie/2004-12-Dec/Unknown Location/2004-12-31_23-01-39-imgp4530.jpg", 
"destination":"/Users/flap/Pictures/elodie/2010-04-Apr/Unknown Location/2010-04-30_22-00-00-imgp4530.jpg"}
```

destination folder should be `2010-05-May`, not `2010-04-Apr`

**Comment by jmathai** [comment]
It's a UTC problem. At the moment what I've been doing is to add my UTC offset when I specify a time but I agree that's probably not a workable solution.

```
--time="2010-05-01 12:00:00"
```

**Comment by jmathai** [comment]
It looks like there's a [timezone EXIF field](http://www.gnomeplanet.com/tutorial/which_time_zone.php) but I'm not sure it's being used. I'm interested in seeing if we can include this as part of the commands which Elodie uses.

I'd love to be able to add in timezone data to all of my photos. Unfortunately I don't know how many programs use it. Doesn't matter to me as long as we're persisting this information correctly in the photo itself.

**Comment by Constm** [comment]
Hi,

This is reproducible not only with update command, but during regular scan/processing as well. This issue results in incorrect file names if TS is used as part of file name and incorrect folder structure and photo placement if date is used as source of folder structure: e.g. photo taken in UTC-5 time zone few minutes before New Year will be placed in completely wrong year, month, day folder... 

There is GPS Date/Time field in EXIF. Is it possible to calculate the difference between GPS Date/Time and  Date/Time Original and properly use date and time? 

Thanks,
Konstantin.
