### ISSUE TITLE
Generated documentation

### ISSUE THREAD

**Issue by noonat** [jmathai/elodie#70]
It would be useful to have some generated code documentation. I noticed you're annotating some functions with `@param` etc. Are these actually being used to generate documentation somewhere?

If not, would you be open to a pull request that adds additional docstrings and modifies things so docs could be generated with [Sphinx](http://sphinx-doc.org/) (and perhaps hosted on [readthedocs](https://readthedocs.org))?

**Comment by jmathai** [comment]
Absolutely. No docs are being generated at the moment but using readthedocs would be great. Sphinx is also great.

I imagine we'll need to change the comment blocks a little bit to conform to the documentation generation library.
