### ISSUE TITLE
Add requirements.txt?

### ISSUE THREAD

**Issue by arikfr** [jmathai/elodie#76]
Until elodie becomes a pip package (#41), I recommend adding a requirements.txt file to the project, to make sure that everyone is using the correct versions of the dependencies.

**Comment by noonat** [comment]
There's a requirements.txt in the docs folder for ReadTheDocs. Maybe it should be moved to the root and have some version specifications added to it?

**Comment by jmathai** [comment]
@noonat if that works with the docs then I think it's two birds with one stone.

**Comment by arikfr** [comment]
Actually I wouldn't merge the two. Not everyone who runs elodie needs to
build the docs.

**Comment by noonat** [comment]
@arikfr @jmathai I opened #80 for this.

**Comment by jmathai** [comment]
Closed in PR gh-80.
