### ISSUE TITLE
Support .MPG files

### ISSUE THREAD

**Issue by davisonio** [jmathai/elodie#85]
The MPEG is quite a common video format so it'd be great it elodie supported it :)
```
{"source":"/Users/craig/Pictures/Craig/Old Photos/2006/MOV00918.MPG", "error_msg":"Not a supported file"}
```

**Comment by jmathai** [comment]
MPEGs probably work just fine. Do you mind adding `mpg` (and prolly `mpeg` if you can test) to `video.py`? https://github.com/jmathai/elodie/blob/master/elodie/media/video.py#L35

If that works could you submit a PR with that change? Else I'll look into how to support MPEG.

**Comment by jmathai** [comment]
Closed in gh-87.
