### ISSUE TITLE
segfaults for me on OSX 10.11 with brew python 2.7.11

### ISSUE THREAD

**Issue by fred-brunner** [jmathai/elodie#91]
Followed the README install procedure, but I'm getting an immediate segfault when I run the script, regardless of the input.

./elodie.py     
zsh: segmentation fault  ./elodie.py

**Comment by fred-brunner** [comment]
Apparently a problem with pyexiv2, reinstalled it and seems to be working now, sorry for the noise.

**Comment by jmathai** [comment]
@fred-brunner any idea what the problem was? I recall someone else reporting a similar issue but I can't find it. Glad you got it sorted out.

**Comment by fred-brunner** [comment]
Not exactly sure. I believe that I may have done the brew installs first because I was intending to use the system Python. This failed because pip, which I didn't want to install sudo, so I installed Python from brew and then installed pip and did the requirements.txt import. This resulted in the segfault when trying to load pyexiv2. Once it occurred to me to launch elodie.py verbose and saw the problem, I just brew uninstalled and reinstalled the package, which magically fixed it :/

**Comment by jmathai** [comment]
Thanks. We'll keep an eye out for problems in the future.
