### ISSUE TITLE
Support for RAW files?

### ISSUE THREAD

**Issue by fred-brunner** [jmathai/elodie#92]
My camera (Panasonic GX7) creates RAW files with an *.RW2 suffix, which have full EXIF information, but elodie ignores these. The EXIF information is read fine by Lightroom/GraphicConverter, etc. Is this just a file suffix restriction, or is it that the file type is actually unsupported?

**Comment by jmathai** [comment]
We've whitelisted the formats that have been tested. Can you add `rw2` to the list here and see if it works?

https://github.com/jmathai/elodie/blob/master/elodie/media/photo.py#L30

**Comment by fred-brunner** [comment]
Worked a charm. I'd submit a pull, but seems kind of trivial ;)

**Comment by jmathai** [comment]
@fred-brunner you could add a test to accompany a PR. Else I can do it but if you can provide an RW2 file I can add it to the test suite then that'd be great.

**Comment by jmathai** [comment]
Created gh-93 for adding tests for RW2 files. @fred-brunner can you provide an RW2 file we can use for tests?

**Comment by jmathai** [comment]
Created gh-94 to track the lack of support from pyexiv2 to write EXIF. Only needed if you want to use Elodie to update the EXIF on an RW2 file.

**Comment by fred-brunner** [comment]
I have a file I can provide, but I apparently can't submit a pull for this repo...

**Comment by jmathai** [comment]
@fred-brunner you'd have to fork it, push a commit to your fork and then submit a pull request from there.

I found another RW2 file online and added tests for it. It revealed what `pyexiv2` can read EXIF but not write EXIF to RW2 files. see gh-94 for details.

**Comment by fred-brunner** [comment]
Ok, cool - hopefully pyexiv2 will add that capability...
