### ISSUE TITLE
Is there a place for "Event" metadata in the directory path?

### ISSUE THREAD

**Issue by Ramblurr** [jmathai/elodie#96]
This issue is probably a feature request.

I currently organize my photos in a similar directory structure, with the addition of event meta data in the folder name.

These event names are optional, and they let me quickly identify what was going on on that day/month.

Assuming I live in New York, I might have many, many photos taken in New York. So for example instead of `2014-03-Mar/New York/`, I label mine folders `2014-03-Mar/New York - Alice Birthday` . 

These aren't albums strictly speaking, just an additional piece of metadata to help remind me what was going on.

This doesn't look possible in the current version of elodie, and I would love to see it, but obviously would have to be implemented so it is useful for most people. This might be straying too far into traditional photo organizational territory, but I personally find huge list of timestamped directories filled with similar location names quite cumbersome to navigate.

What does the community think?

**Comment by jmathai** [comment]
@Ramblurr Albums might be what you're looking for. Elodie supports a custom EXIF tag which is used to store album information and maps to the file system.

```
./elodie.py update --album="New York - Alice Birthday" file1.jpg file2.jpg
```

If a photo already contains this EXIF tag then it will be properly placed into the correct folder.

This is also supported in the GUI with an Album field you can use.

Try it and close this issue if it does what you're looking for.

**Comment by Ramblurr** [comment]
Oh that's great! Does it affect the folder naming structure?

**Comment by jmathai** [comment]
Just closing the loop. Yes it does affect the folder naming in the way I
believe you described.

On Saturday, March 26, 2016, Casey Link <notifications@github.com> wrote:

> Oh that's great! Does it affect the folder naming structure?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jmathai/elodie/issues/96#issuecomment-201916153>
>


-- 
-- Snet form my mobl phoone
